export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  date: string; // ISO format, e.g. "2026-06-01"
  readTime: string;
  image: string; // path under /public, e.g. "/blog/slug.svg"
  content: string[]; // array of paragraphs / section text (rendered as <p> or <h2> if prefixed with "## ")
}

export const blogPosts: BlogPost[] = [
  {
    slug: "merge-pdf-without-losing-quality",
    image: "/blog/merge-pdf-without-losing-quality.svg",
    title: "How to Merge PDF Files Without Losing Quality",
    description:
      "Combining PDFs is easy, but it's just as easy to end up with a bloated or blurry file if you use the wrong method. Here's how to do it right.",
    category: "Guides",
    date: "2026-05-02",
    readTime: "5 min read",
    content: [
      "Merging PDF files sounds simple until you actually try it with a mix of scanned documents, screenshots, and text-based pages. The most common mistake people make is merging with a tool that flattens every page into a low-resolution image, which quietly destroys text sharpness and makes the file look worse than the originals.",
      "## Why quality loss happens during merging",
      "Some merge tools re-render every page instead of copying the underlying PDF objects. Re-rendering is faster to build into software, but it strips out vector text and recompresses images, which is why a merged file can look noticeably worse than the source documents even though nothing was supposed to change.",
      "A properly built merge tool copies the page objects directly from each source file and stitches them together without re-encoding anything. That's the difference between a merge that preserves your original fonts and image resolution and one that doesn't.",
      "## Steps to merge PDFs without quality loss",
      "Start by making sure every source file is already in the resolution and quality you want, since merging can't add back detail that isn't there. Upload your files in the order you want them to appear, or upload them in any order and reorder using drag-and-drop before combining. Run the merge and download the result, then open it and check a few pages at 100% zoom to confirm text is still crisp and images haven't been recompressed.",
      "## When file size matters more than perfect preservation",
      "If your merged file is too large to email or upload somewhere, that's a separate step: compress after merging, not before. Compressing first and merging second means you're combining already-degraded files. Compressing after merging gives you control over exactly how much quality you're trading for file size.",
      "## A quick checklist",
      "Keep source files in their original quality, merge in the correct page order, verify the output at full zoom before sending it anywhere, and only compress afterward if size is genuinely a problem. Following that order avoids the two most common complaints people have with merged PDFs: blurry pages and unnecessarily huge files.",
    ],
  },
  {
    slug: "reduce-pdf-file-size-without-losing-quality",
    image: "/blog/reduce-pdf-file-size-without-losing-quality.svg",
    title: "How to Reduce PDF File Size Without Losing Quality",
    description:
      "Large PDFs bounce off email attachment limits and slow down uploads. Here's what actually shrinks a file size without turning your pages to mush.",
    category: "Guides",
    date: "2026-05-05",
    readTime: "6 min read",
    content: [
      "Most of the size in a bloated PDF comes from images, not text. A ten-page contract with no images might be 200KB, while a ten-page scanned document with full-resolution photos can easily hit 40MB. Understanding that difference is the key to compressing smartly instead of blindly.",
      "## What compression actually changes",
      "PDF compression tools typically do two things: downsample embedded images to a lower resolution, and increase JPEG compression on those images. Text and vector graphics are usually left alone, since they take up very little space to begin with and compressing them wouldn't meaningfully reduce file size anyway.",
      "## Choosing a compression level",
      "A light compression setting is usually enough for documents that will only be read on screen, since most monitors can't display more detail than a 150 DPI image provides anyway. A medium setting is a safe default for general sharing. A high compression setting is best reserved for documents you just need to be small and don't need to print, since it will visibly soften photos and scanned text.",
      "## Compressing scanned documents specifically",
      "Scanned pages are the worst offenders because scanners often save at 300 or 600 DPI by default, far higher than needed for reading on a screen. If your original scan is unnecessarily high-resolution, you can often cut file size by 80% or more with almost no visible difference in a compression tool built to handle scans specifically.",
      "## What not to do",
      "Avoid repeatedly compressing the same file through multiple tools or multiple passes, since each pass re-compresses already-lossy images and the quality loss compounds every time. Compress once, check the result, and if it's still too large, go back to your original uncompressed file and try a stronger setting from scratch rather than compressing the already-compressed version again.",
      "## A practical target",
      "Most email providers cap attachments around 25MB, and many web forms cap uploads even lower. If you're aiming to get under a specific limit, it helps to know your target size before you start rather than compressing repeatedly by trial and error.",
    ],
  },
  {
    slug: "convert-pdf-to-word",
    image: "/blog/convert-pdf-to-word.svg",
    title: "How to Convert a PDF to a Word Document",
    description:
      "Converting a PDF to Word works well for some documents and badly for others. Here's how to get an editable result that doesn't fall apart.",
    category: "Guides",
    date: "2026-05-08",
    readTime: "5 min read",
    content: [
      "PDF to Word conversion has a reputation for being unreliable, and that reputation is only half deserved. The outcome depends heavily on how the original PDF was created in the first place.",
      "## Why some conversions look perfect and others don't",
      "A PDF exported directly from Word or Google Docs contains structured text, so converting it back to Word is close to a clean reversal. A PDF that started as a scanned image contains no real text at all, just a picture of text, so a converter has to guess at the words using OCR before it can produce anything editable, and that guessing introduces errors.",
      "## Getting a clean conversion from a text-based PDF",
      "Upload the file, run the conversion, and check that paragraph spacing, bullet points, and any tables came through correctly. Complex multi-column layouts and heavily designed documents are the most likely to shift slightly, since Word's layout engine doesn't handle absolute-positioned text the same way a PDF does.",
      "## Getting a usable conversion from a scanned PDF",
      "For scanned documents, look for a converter that explicitly runs OCR rather than one that just extracts whatever text metadata exists, since scanned pages usually have none. After converting, proofread the result carefully, especially numbers, dates, and any unusual formatting, since OCR mistakes tend to hide in exactly those details.",
      "## What tends to break",
      "Headers, footers, footnotes, and text wrapped around images are the parts most likely to need manual cleanup after conversion. If your document relies heavily on any of these, budget a few minutes to fix formatting after the conversion rather than expecting a perfect one-click result.",
      "## When not to convert at all",
      "If you only need to copy a paragraph or two of text, it's often faster to open the PDF, select the text directly, and paste it into Word rather than converting the whole file. Full conversion is worth it when you need to substantially edit or reformat the entire document.",
    ],
  },
  {
    slug: "split-pdf-into-multiple-files",
    image: "/blog/split-pdf-into-multiple-files.svg",
    title: "How to Split a PDF Into Multiple Files",
    description:
      "Whether you need one page pulled out or a large document broken into chapters, here's how PDF splitting actually works.",
    category: "Guides",
    date: "2026-05-11",
    readTime: "4 min read",
    content: [
      "Splitting a PDF is one of the simpler PDF operations, but there are a few different ways to do it depending on what you actually need out the other end.",
      "## Splitting by page range",
      "If you need specific, contiguous pages, such as pages 5 through 10 of a report, a range split is the right tool. You specify the start and end page and the tool extracts exactly that range as a new file, leaving the original untouched.",
      "## Splitting into individual pages",
      "If you need every page as its own separate file, such as splitting a scanned batch of receipts into one file per receipt, look for a tool that offers a 'split all pages' option rather than manually extracting one range at a time.",
      "## Splitting by file size or page count",
      "Some tools let you split a large document into equal chunks, useful when you need to stay under an upload or email size limit and don't particularly care where the split falls, just that each resulting file is small enough.",
      "## Keeping track of the output",
      "When you split into many files, naming gets messy fast. Most tools will auto-number the output files based on their page numbers, which is usually more useful than generic names, since it lets you tell at a glance which pages ended up in which file.",
      "## A common mistake",
      "People sometimes split a PDF, edit one of the resulting pieces, and then try to merge it back into the original, only to find the page order got scrambled. Always double-check page order after re-merging split files, especially if you edited or renamed pieces out of sequence.",
    ],
  },
  {
    slug: "password-protect-pdf",
    image: "/blog/password-protect-pdf.svg",
    title: "How to Password Protect a PDF",
    description:
      "PDF passwords come in two very different types, and using the wrong one gives you a false sense of security. Here's the difference.",
    category: "Security",
    date: "2026-05-14",
    readTime: "5 min read",
    content: [
      "PDF password protection isn't one feature, it's two, and confusing them is the most common mistake people make when trying to secure a document.",
      "## Open password vs. permissions password",
      "An open password (sometimes called a user password) prevents anyone from opening the file at all without entering it first. A permissions password (or owner password) lets anyone open the file, but restricts what they can do with it, like printing, copying text, or editing. If you actually want to keep a document confidential, you need an open password, not just a permissions password.",
      "## Choosing a strong password",
      "A short password on a PDF is weaker than it feels, since PDF passwords can be cracked with brute-force tools, especially older PDF encryption standards. Aim for at least 12 characters mixing letters, numbers, and symbols, and avoid anything related to the document's content, like a company name or the year.",
      "## Setting permission restrictions",
      "Beyond the password itself, most protection tools let you separately restrict printing, copying, or editing. These restrictions are useful for things like preventing casual copy-pasting of a contract, but they're not a strong security measure on their own since permissions restrictions can be bypassed more easily than a genuine open password.",
      "## Sharing a protected PDF safely",
      "Never send the password in the same email as the protected file. Send the file first, then the password through a separate channel, like a text message or a phone call, so that anyone who intercepts one doesn't automatically get the other.",
      "## Removing protection later",
      "If you set a password and later need to remove it, you'll need the original password to unlock the file first. There's no legitimate way to remove a PDF password you don't know, which is exactly the point of the feature, so keep your passwords somewhere you won't lose them.",
    ],
  },
  {
    slug: "remove-password-from-pdf",
    image: "/blog/remove-password-from-pdf.svg",
    title: "How to Remove a Password From a PDF",
    description:
      "If you own the file and know the password, removing it is quick. Here's how it works and what to watch out for.",
    category: "Security",
    date: "2026-05-16",
    readTime: "3 min read",
    content: [
      "Removing a password from a PDF you legitimately own is a common need, usually because the file is going to be stored somewhere already secure and the extra password step has become an annoyance rather than a protection.",
      "## What you need before starting",
      "You'll need to know the current password. A password removal tool decrypts the file using the password you provide; it doesn't crack or guess it. If you've genuinely forgotten the password, that's a different and much harder problem, and most legitimate tools won't help you bypass a password you don't know.",
      "## The removal process",
      "Upload the protected PDF, enter the current password when prompted, and the tool will produce a new copy of the file without any password requirement. The original protected file isn't modified, so if something goes wrong you still have your protected version to try again.",
      "## A note on permissions restrictions",
      "If your file has printing or editing restrictions set through an owner password rather than a full open password, some tools can remove those restrictions even without knowing the original password, since the file itself isn't locked, only certain actions on it are limited. This is a legal gray area depending on why the restriction was set, so only do this on documents you have the rights to modify.",
      "## Keep a backup",
      "Before removing password protection from an important document, keep a copy of the original protected file somewhere safe, just in case you need the protected version again later, like for archival or compliance reasons.",
    ],
  },
  {
    slug: "convert-image-to-pdf",
    image: "/blog/convert-image-to-pdf.svg",
    title: "How to Convert Images to PDF",
    description:
      "Turning JPGs or PNGs into a PDF is useful for everything from scanned receipts to portfolios. Here's how to do it cleanly.",
    category: "Guides",
    date: "2026-05-19",
    readTime: "4 min read",
    content: [
      "Converting images to PDF is one of the most common reasons people reach for a PDF tool, usually to combine several photos of a document, like a multi-page contract photographed with a phone, into a single shareable file.",
      "## Getting page order right",
      "When you upload multiple images, most tools will order them alphabetically by filename by default, which rarely matches the order you actually photographed the pages in. Rename your files with a number prefix (01, 02, 03) before uploading, or use a tool that lets you drag to reorder pages before generating the PDF.",
      "## Matching page size to your content",
      "Photos of documents are usually best converted using a page size that matches standard paper, like A4 or Letter, so the resulting PDF prints and displays the way people expect. Photos meant to be viewed as images, like a portfolio, often look better if the page size matches the image's own aspect ratio instead.",
      "## Improving photo quality before converting",
      "If you're photographing paper documents with a phone camera, take the photo in good, even lighting and hold the camera as directly overhead as possible to avoid the perspective distortion that makes text harder to read. A tool with an auto-crop or auto-straighten feature for scanned photos can fix minor issues, but starting with a clear photo saves a step.",
      "## One image per page vs. combined layouts",
      "Most conversion tools default to one image per page. If you want to fit two smaller images on a single page, like receipts, check whether your tool supports a grid layout option, since not all of them do, and you may need a separate layout step afterward.",
    ],
  },
  {
    slug: "convert-pdf-to-jpg-png",
    image: "/blog/convert-pdf-to-jpg-png.svg",
    title: "How to Convert PDF Pages to JPG or PNG",
    description:
      "Sometimes you need an image, not a document. Here's how PDF-to-image conversion works and which format to pick.",
    category: "Guides",
    date: "2026-05-22",
    readTime: "3 min read",
    content: [
      "Converting a PDF page into an image file is useful when you need to drop a page into a slideshow, a website, or a social post where a PDF simply won't display the way an image will.",
      "## JPG vs. PNG for converted PDF pages",
      "JPG is the better choice for pages with photos or complex color, since it compresses well and keeps file sizes small. PNG is the better choice for pages that are mostly text, diagrams, or line art, since PNG compression doesn't introduce the blurring artifacts JPG does around sharp edges and text.",
      "## Choosing the right resolution",
      "A low resolution export is fine for viewing on screen, but will look pixelated if you try to print it or zoom in. If there's any chance the image will be printed or displayed large, export at a higher resolution setting even though it produces a bigger file.",
      "## Converting multi-page documents",
      "If your PDF has multiple pages, most converters will let you choose between converting every page into a separate image file (often delivered as a zip) or converting just the specific pages you select. Decide which you need before starting, since re-running the conversion for a single missed page is an easy extra step to avoid.",
      "## What gets lost in the conversion",
      "Once converted to an image, any selectable text, links, or form fields in the original PDF are gone; it's now just a picture. If you need the recipient to be able to search or copy text, keep the PDF and don't convert it, or provide both formats.",
    ],
  },
  {
    slug: "add-digital-signature-to-pdf",
    image: "/blog/add-digital-signature-to-pdf.svg",
    title: "How to Add a Digital Signature to a PDF",
    description:
      "Not all electronic signatures are equal. Here's the difference between a drawn signature and a cryptographic digital signature, and when you need each.",
    category: "Security",
    date: "2026-05-25",
    readTime: "5 min read",
    content: [
      "The term 'digital signature' actually covers two quite different things, and knowing which one you need matters more than most people realize.",
      "## Electronic signature vs. true digital signature",
      "An electronic signature is typically a drawn, typed, or uploaded image of your signature placed onto the page. It's fast and works for most everyday documents, but it doesn't cryptographically prove who signed the file or verify the document hasn't been altered afterward. A true digital signature uses a certificate-based cryptographic key, which does both of those things, and is what's required for many legal, government, or high-stakes business documents.",
      "## Adding a simple electronic signature",
      "Upload your PDF, draw your signature with a mouse or trackpad, type your name and pick a script-style font, or upload a photo of your handwritten signature on paper. Then place it on the appropriate line and save. This works well for informal agreements, internal approvals, and most day-to-day paperwork.",
      "## Adding a certificate-based digital signature",
      "This requires a digital certificate, either from a certificate authority or generated within signing software, and produces a signature that can be verified cryptographically and will show a warning in PDF readers if the document is altered after signing. This is the appropriate choice for contracts, legal filings, and anything where you need to prove authenticity later.",
      "## Multiple signers",
      "If a document needs several people to sign, decide upfront whether you need them to sign in a specific order or simultaneously, since some documents (like approvals that depend on an earlier signature being valid) need sequential signing while others don't. Track which version of the file each signer is working from to avoid signatures ending up on outdated copies.",
    ],
  },
  {
    slug: "rotate-pages-in-pdf",
    image: "/blog/rotate-pages-in-pdf.svg",
    title: "How to Rotate Pages in a PDF",
    description:
      "A sideways scan is a small annoyance with a quick fix. Here's how to rotate one page or an entire document.",
    category: "Guides",
    date: "2026-05-28",
    readTime: "3 min read",
    content: [
      "Sideways or upside-down pages are one of the most common small annoyances in PDFs, usually caused by a scanner that fed a page in the wrong orientation.",
      "## Rotating the whole document",
      "If every page came out rotated the same way, which is common with scanned batches, look for a 'rotate all pages' option that applies a single rotation to the entire file in one step rather than making you fix each page individually.",
      "## Rotating individual pages",
      "Mixed orientation is common in scanned documents that include both portrait pages and landscape tables or charts. Most rotation tools let you select specific pages and rotate only those, leaving the rest of the document untouched.",
      "## 90, 180, or 270 degrees",
      "Sideways pages need a 90 degree rotation in one direction or the other, while a page that scanned completely upside down needs a full 180 degree rotation. If you're not sure which direction is correct, rotate 90 degrees and check the preview before saving, since rotating the wrong direction just makes it sideways the other way.",
      "## Saving the rotation permanently",
      "Some PDF viewers let you rotate a page for viewing only, which resets the next time the file is opened, rather than actually saving the rotation into the file. Make sure you're using a tool that permanently applies and saves the rotation if you plan to share the file with someone else.",
    ],
  },
  {
    slug: "remove-pages-from-pdf",
    image: "/blog/remove-pages-from-pdf.svg",
    title: "How to Remove Pages From a PDF",
    description:
      "Deleting a blank page or an outdated section shouldn't require rebuilding the whole document. Here's the fast way.",
    category: "Guides",
    date: "2026-05-30",
    readTime: "3 min read",
    content: [
      "Removing pages from a PDF is a common cleanup task, whether you're deleting a blank scanned page, an outdated appendix, or a cover sheet that no longer applies.",
      "## Selecting pages to remove",
      "Most page-removal tools show a thumbnail preview of every page, letting you click to select the ones you want gone before confirming. This is far more reliable than typing page numbers, since it's easy to miscount pages in a long document, especially if the visible page numbers printed on the pages don't match the PDF's actual page order.",
      "## Removing several non-contiguous pages",
      "If you need to remove pages 3, 7, and 12 but keep everything else, look for a tool that accepts multiple individual page selections rather than only a single continuous range, since range-only tools will force you to do several separate passes.",
      "## What happens to page numbers",
      "Removing pages doesn't renumber any page numbers that are printed as part of the content itself, since those are just part of the page image or text, not a property of the PDF. If the document has printed page numbers, you may need a separate step to fix them after removing pages, especially for formal documents.",
      "## Double-check before finalizing",
      "Always preview the resulting document after removing pages, particularly for documents like contracts or reports where an accidentally removed page could change the meaning of the document, not just its length.",
    ],
  },
  {
    slug: "extract-pages-from-pdf",
    image: "/blog/extract-pages-from-pdf.svg",
    title: "How to Extract Pages From a PDF",
    description:
      "Need just a few pages out of a much longer document? Here's how extraction differs from splitting or deleting.",
    category: "Guides",
    date: "2026-06-02",
    readTime: "3 min read",
    content: [
      "Extracting pages is essentially the mirror image of removing pages: instead of deleting the pages you don't want, you pull out only the pages you do want and save them as a new file, leaving the original document untouched.",
      "## When to extract instead of split",
      "Splitting typically implies breaking a whole document into several complete pieces. Extraction is more targeted, useful when you just need, say, pages 4 and 9 out of a 40-page report and don't care about the rest becoming separate files at all.",
      "## Extracting a single range vs. scattered pages",
      "If the pages you need are consecutive, a simple start-and-end range is enough. If you need non-consecutive pages, like page 2, page 15, and page 30, make sure your tool supports selecting individual, non-adjacent pages in one extraction rather than requiring several separate exports.",
      "## Preserving quality during extraction",
      "A well-built extraction tool copies the selected pages directly without re-rendering them, meaning fonts, image resolution, and any interactive elements like form fields or links on those pages are preserved exactly as they were in the source file.",
      "## A common use case",
      "Extraction is especially useful for pulling a single signed page, like a signature page or a specific exhibit, out of a much larger legal or contract document without needing to send the entire original file.",
    ],
  },
  {
    slug: "add-watermark-to-pdf",
    image: "/blog/add-watermark-to-pdf.svg",
    title: "How to Add a Watermark to a PDF",
    description:
      "Watermarks protect drafts and brand documents, but a badly placed one can make a document unreadable. Here's how to get it right.",
    category: "Guides",
    date: "2026-06-05",
    readTime: "4 min read",
    content: [
      "Watermarking a PDF is common for marking drafts, protecting confidential documents, or adding a company logo across every page, but a poorly configured watermark can end up making the document harder to read than it protects.",
      "## Text watermarks vs. image watermarks",
      "A text watermark, like 'DRAFT' or 'CONFIDENTIAL', is quick to set up and works well for internal documents. An image watermark, like a company logo, takes a bit more setup but looks more polished for anything client-facing or public.",
      "## Getting opacity right",
      "The most common watermarking mistake is leaving the opacity too high, which makes the underlying text hard to read. A lower opacity setting, generally in the 10-20% range, is usually enough to be visible without interfering with readability, especially for text-heavy documents.",
      "## Placement and rotation",
      "A diagonal watermark placed across the center of the page is the standard choice because it's hard to crop out and doesn't sit directly on top of any single line of text. A watermark placed in a corner is easier to read past, but is also easier for someone to simply crop off if the point is to discourage misuse.",
      "## Applying to specific pages only",
      "You don't always need a watermark on every page. Some tools let you apply it only to specific pages, like just the cover page for a draft stamp, or skip watermarking on pages that are purely blank or purely images, which can matter for documents you want to look professional in some sections and clearly marked as a draft in others.",
    ],
  },
  {
    slug: "ocr-scanned-pdf-to-text",
    image: "/blog/ocr-scanned-pdf-to-text.svg",
    title: "How to Use OCR to Extract Text From Scanned PDFs",
    description:
      "A scanned PDF is just a picture of text until OCR turns it into something you can actually search, copy, and edit. Here's how it works.",
    category: "Guides",
    date: "2026-06-08",
    readTime: "6 min read",
    content: [
      "A scanned document, no matter how clean it looks, contains no real text at all as far as a computer is concerned; it's just a photograph of a page. OCR, or optical character recognition, is the technology that reads the shapes on that image and converts them into actual, searchable, selectable text.",
      "## Why OCR accuracy varies so much",
      "OCR accuracy depends heavily on the quality of the source scan. A clean, high-contrast scan of a typed document can often be recognized with 99%+ accuracy. A blurry photo of a handwritten note, faded ink, or a low-resolution fax can drop accuracy dramatically, sometimes to the point of being unusable without heavy manual correction.",
      "## Improving your source scan before running OCR",
      "Scan at a resolution of at least 300 DPI for text documents, make sure the page is well-lit and not photographed at an angle, and avoid shadows falling across the text. If you're scanning with a phone rather than a proper scanner, use an app or tool with auto-crop and auto-straighten features to reduce distortion before running OCR.",
      "## What OCR gives you",
      "A good OCR tool doesn't just extract raw text, it can produce a searchable PDF that looks identical to the scanned original but has an invisible text layer underneath, letting you search, copy, and highlight text while keeping the original page appearance intact.",
      "## Handling multiple languages",
      "Most OCR engines need to know which language they're reading in order to recognize characters accurately, especially for non-Latin scripts. If your document mixes languages, check whether your OCR tool supports multi-language detection, since forcing a single-language setting on a mixed document will produce garbled results in the wrong-language sections.",
      "## Proofreading after OCR",
      "Even highly accurate OCR makes mistakes, particularly with numbers (where a '0' and an 'O' or a '1' and an 'l' look similar), so always proofread OCR output for anything that matters, like financial figures, dates, or names, rather than trusting it blindly.",
    ],
  },
  {
    slug: "pdf-vs-word-vs-google-docs",
    image: "/blog/pdf-vs-word-vs-google-docs.svg",
    title: "PDF vs Word vs Google Docs: Which Should You Use?",
    description:
      "Each format has a job it's genuinely good at. Here's how to pick the right one instead of defaulting to whatever's familiar.",
    category: "Comparisons",
    date: "2026-06-11",
    readTime: "5 min read",
    content: [
      "It's easy to default to whichever format you're most used to, but PDF, Word, and Google Docs are built for genuinely different purposes, and picking the right one saves headaches later.",
      "## PDF: for final, fixed documents",
      "A PDF is designed to look exactly the same on every device and every printer, regardless of what software or fonts the recipient has installed. That makes it the right choice for anything that's finished and shouldn't change: contracts, invoices, resumes, official reports, and anything you're sending to someone outside your organization.",
      "## Word: for structured editing with formatting control",
      "A Word document is the right format when the recipient genuinely needs to edit the content, especially documents with complex formatting like styles, tables of contents, and templates that need to be reused. Word also remains the standard format expected by many corporate and legal workflows, particularly ones using tracked changes.",
      "## Google Docs: for real-time collaboration",
      "Google Docs is built for multiple people editing the same document at the same time, with automatic saving and simple version history. It's the right choice for drafts, brainstorming, and any document that's actively being worked on collaboratively rather than finished and being distributed.",
      "## Converting between formats",
      "It's common to draft in Google Docs or Word for the editing flexibility, then export to PDF once the document is finalized and ready to share or archive, so the final version stays fixed and can't be accidentally altered by whoever receives it.",
      "## The core rule of thumb",
      "If the document is still being worked on, use Word or Google Docs. If the document is finished and needs to look the same for everyone who opens it, convert it to PDF before sending.",
    ],
  },
  {
    slug: "fill-out-pdf-form-online",
    image: "/blog/fill-out-pdf-form-online.svg",
    title: "How to Fill Out a PDF Form Online",
    description:
      "Some PDF forms are fillable, some aren't, and treating them the same way leads to messy printouts. Here's how to tell the difference and fill either kind properly.",
    category: "Guides",
    date: "2026-06-14",
    readTime: "4 min read",
    content: [
      "PDF forms come in two very different types, and knowing which kind you're dealing with changes how you should fill it out.",
      "## Fillable forms vs. flat forms",
      "A fillable, or interactive, PDF form has actual form fields built in: text boxes, checkboxes, and dropdowns that you can click into directly. A flat form is just a regular page with lines and boxes drawn on it, with no interactive fields at all, meaning you can't click into it the way you can with a fillable form.",
      "## Filling a fillable form",
      "Open the form in a PDF viewer that supports form fields, click into each field, and type your answers directly. Most PDF viewers will show a highlighted border or cursor when you hover over an actual form field, which is a quick way to confirm the form is genuinely fillable before you start.",
      "## Filling a flat, non-fillable form",
      "For a flat form, you'll need a PDF editor's text tool to manually place text boxes onto the page in the right spots, essentially typing 'over' the printed lines. This takes a bit more care to align the text correctly, but it produces a much cleaner result than printing the form and filling it by hand.",
      "## Checkboxes and signatures on flat forms",
      "For checkbox-style options on a flat form, most editors let you insert a simple checkmark or X symbol you can place precisely where needed. For a signature line, use a signature tool to draw or place your signature image directly onto the line rather than trying to draw it accurately with a text tool.",
      "## Saving your filled form",
      "Always save a copy of the completed form for your own records before submitting it, especially for anything official, since some submission methods, like uploading to a portal, won't give you a copy back afterward.",
    ],
  },
  {
    slug: "organizing-digital-documents",
    image: "/blog/organizing-digital-documents.svg",
    title: "Best Practices for Organizing Digital Documents",
    description:
      "A messy downloads folder full of scan(1).pdf, scan(2).pdf is a solvable problem. Here's a simple system that actually holds up over time.",
    category: "Productivity",
    date: "2026-06-17",
    readTime: "5 min read",
    content: [
      "Most people's document chaos isn't caused by having too many files, it's caused by having no consistent system for naming and storing them, so files pile up wherever they happened to land.",
      "## A simple, consistent naming convention",
      "A reliable format is date, then description, then version, like '2026-06-17_electricity-bill_final.pdf'. Starting with the date means files automatically sort chronologically in any file browser, which is often the most useful sort order for finding something later.",
      "## Folder structure that scales",
      "A folder structure with too many nested levels becomes as hard to navigate as no structure at all. A simple two or three level structure, like Category > Year > Files, tends to hold up much better over time than an elaborate hierarchy that made sense on day one but becomes a maze after a year of use.",
      "## Dealing with scanned paperwork",
      "Scan documents as soon as they arrive rather than letting physical paper pile up, and OCR them so they're searchable later. A folder full of scanned PDFs you can't search by content is barely more useful than a physical filing cabinet.",
      "## Version control without the mess",
      "Avoid ending up with 'contract_final.pdf', 'contract_final_v2.pdf', and 'contract_final_ACTUALLY_final.pdf'. Use a simple incrementing version number in the filename, and once a document is genuinely final, rename it clearly and archive the earlier drafts into a separate subfolder instead of leaving them all in the same place.",
      "## Backing it all up",
      "Whatever system you use, make sure it's backed up somewhere other than a single laptop hard drive, whether that's cloud storage, an external drive, or both. An organized set of files does no good if it's lost entirely because of a single device failure.",
    ],
  },
  {
    slug: "compress-pdf-for-email",
    image: "/blog/compress-pdf-for-email.svg",
    title: "How to Compress a PDF for Email",
    description:
      "Email attachment limits are stricter than most people realize. Here's how to get a PDF small enough to send without stripping out what matters.",
    category: "Guides",
    date: "2026-06-20",
    readTime: "4 min read",
    content: [
      "Most email providers cap attachments somewhere between 20 and 25MB, and a lot of everyday PDFs, especially scanned ones, blow past that limit without the sender realizing it until the email bounces.",
      "## Check your actual limit first",
      "Attachment limits vary by provider and sometimes by the recipient's mailbox settings too, not just your own. If you're not sure, aim conservatively for under 10MB, which comfortably clears almost every provider's limit including ones with unusually strict settings.",
      "## Compressing before sending",
      "Run your file through a compression tool set to a medium compression level as a starting point, which usually cuts file size significantly while keeping text and images clearly legible. Check the resulting file size and only step up to a higher compression level if it's still too large.",
      "## When compression alone isn't enough",
      "If a single PDF is genuinely too large even after compression, like a lengthy document full of high-resolution scans, consider splitting it into two smaller files and sending them separately, or uploading it to a cloud storage link instead of attaching it directly.",
      "## Compressing multiple attachments at once",
      "If you're sending several PDFs together, remember that email limits typically apply to the total size of all attachments combined, not each file individually. Compress every file in the batch, not just the largest one, since several medium-sized files can add up to more than the limit just as easily as one large file can.",
    ],
  },
  {
    slug: "common-pdf-errors-and-fixes",
    image: "/blog/common-pdf-errors-and-fixes.svg",
    title: "Common PDF Errors and How to Fix Them",
    description:
      "From 'file damaged' warnings to fonts that won't display, here are the most common PDF problems and the quickest way to solve each one.",
    category: "Troubleshooting",
    date: "2026-06-23",
    readTime: "6 min read",
    content: [
      "PDFs are generally reliable, but a handful of errors come up often enough that it's worth knowing the quick fix before assuming the file is a lost cause.",
      "## 'The file is damaged and could not be repaired'",
      "This usually means the file got corrupted during a transfer, like an interrupted download or an incomplete upload. Try re-downloading or re-requesting the file from its original source first, since a repair tool can sometimes recover a genuinely corrupted structure but often can't fully fix severe corruption.",
      "## Fonts displaying incorrectly or as boxes",
      "This happens when a PDF references a font that isn't embedded in the file and isn't installed on the device opening it, so the viewer substitutes a fallback font or shows blank boxes instead. The permanent fix is to re-export the original document with fonts embedded, which most PDF creation tools support as an export option.",
      "## Blurry text after opening on a different device",
      "This is often just a rendering artifact from the PDF viewer's zoom level rather than an actual problem with the file. Try zooming to 100% or higher rather than trusting a shrunk-down preview, and if it's still blurry at full zoom, the underlying image was likely compressed too aggressively when the file was created.",
      "## 'This document is password protected' when you don't remember setting one",
      "Some tools apply an owner-level restriction password automatically to prevent editing, without ever asking you to set one, which can be confusing if you weren't expecting it. Check whether it's actually blocking you from opening the file (a real problem) or just blocking editing or printing (a permissions restriction, not a lock).",
      "## Pages appearing out of order after editing",
      "This usually happens after merging, splitting, or reordering pages in a tool that doesn't clearly show a page order preview before saving. Always check the full page thumbnail view before finalizing any operation that changes page order, rather than assuming the tool got it right.",
      "## The file won't open at all in a browser but opens fine in a dedicated PDF app",
      "Browser-based PDF viewers are sometimes stricter about malformed PDF structure than dedicated desktop readers. If a file won't open in-browser, try a dedicated PDF reader app instead, which is often more forgiving of minor structural quirks.",
    ],
  },
  {
    slug: "edit-text-in-pdf",
    image: "/blog/edit-text-in-pdf.svg",
    title: "How to Edit Text in a PDF File",
    description:
      "PDFs weren't originally built to be edited, but modern tools make it possible. Here's what works well and what to expect from the process.",
    category: "Guides",
    date: "2026-06-26",
    readTime: "5 min read",
    content: [
      "PDF was originally designed as a fixed, final format, not an editable one, which is exactly why editing text in a PDF still feels a bit different from editing in a word processor.",
      "## Editing text-based PDFs",
      "If your PDF was created from a text-based source like Word or Google Docs, the text is stored as real, selectable characters, and a PDF editor can let you click directly on a line of text and modify it in place, matching the existing font and size automatically.",
      "## Editing scanned PDFs",
      "A scanned PDF has no real text to click on, only an image. To edit it, you either need to run OCR first to create an editable text layer, or you need to cover the existing text with a white box and type new text on top, which works but doesn't perfectly match the original font.",
      "## Matching fonts and formatting",
      "When you add or edit text in a PDF, a good editor will try to detect and match the surrounding font automatically. For unusual or custom fonts, an exact match isn't always possible, and the tool may substitute the closest available font, which can look slightly different if you zoom in closely.",
      "## Editing tables and columns",
      "Multi-column layouts and tables are the trickiest thing to edit directly in a PDF, since the underlying structure doesn't work the same way it does in a word processor. For heavy table or column edits, it's often easier to convert the PDF to Word first, make the changes there, and convert back to PDF once finished.",
      "## What to check after editing",
      "After making edits, zoom in and check that new text aligns properly with surrounding content and that nothing overlaps or got pushed off the page, especially if you added a longer replacement for a shorter piece of original text.",
    ],
  },
  
  {
    slug: "convert-pdf-to-excel",
    image: "/blog/convert-pdf-to-excel.svg",
    title: "How to Convert a PDF to Excel",
    description:
      "Pulling tables out of a PDF and into a working spreadsheet is trickier than it sounds. Here's how to get clean, usable data.",
    category: "Convert",
    date: "2026-06-29",
    readTime: "5 min read",
    content: [
      "PDF to Excel conversion is one of the more demanding conversions, because it's not just extracting text, it's trying to reconstruct rows, columns, and cell boundaries from something that was never truly structured as a spreadsheet.",
      "## Why table conversion is harder than text conversion",
      "A PDF doesn't actually store 'tables' as a data structure. What looks like a table is really just text and lines positioned at specific coordinates on the page. A converter has to infer where columns and rows begin and end purely from that visual layout, which works well for clean, simple tables and struggles with merged cells, nested tables, or inconsistent spacing.",
      "## Getting the cleanest conversion",
      "Tables with clear grid lines and consistent column widths convert far more reliably than tables that rely purely on whitespace to separate columns. If you have a choice in how the source PDF was generated, a version with visible borders will convert more accurately than a borderless one.",
      "## What to check after converting",
      "Always open the resulting spreadsheet and check that numbers landed in the correct columns, especially in tables with many similar-looking columns of figures. Merged header cells are the most common thing to break, often splitting unpredictably across several columns after conversion.",
      "## When to convert vs. when to copy manually",
      "For a single small table, it's sometimes faster to manually retype the data than to convert an entire multi-page PDF and hunt for one table inside it. Full conversion earns its keep when you're dealing with several pages of tabular data you need to analyze, sort, or run formulas on.",
      "## Formulas and formatting after conversion",
      "Converted spreadsheets bring over the values as static text or numbers, not any formulas that may have originally generated them, since a PDF has no concept of formulas. You'll need to rebuild any calculations you need directly in Excel after conversion.",
    ],
  },
  {
    slug: "convert-excel-to-pdf",
    image: "/blog/convert-excel-to-pdf.svg",
    title: "How to Convert Excel to PDF",
    description:
      "A spreadsheet that looks fine on your screen can print as a dozen cut-off pages. Here's how to convert it to PDF properly.",
    category: "Convert",
    date: "2026-07-01",
    readTime: "4 min read",
    content: [
      "Converting Excel to PDF seems trivial until the output comes out as fifteen pages of awkwardly split columns instead of the clean one-page summary you expected.",
      "## Why Excel-to-PDF often looks wrong",
      "Excel's print area and page layout settings, not just your data, determine what ends up in the PDF. If you never set a print area, Excel will try to print every cell with data in it, often splitting wide tables across several pages in a way that makes them hard to read.",
      "## Setting the print area first",
      "Before converting, select just the cells you actually want in the PDF and set them as the print area under the Page Layout tab. This alone fixes the majority of messy Excel-to-PDF conversions, since it stops Excel from guessing what you wanted included.",
      "## Fitting everything on one page",
      "Use the 'Scale to Fit' option under Page Layout to shrink wide tables down to fit the page width, rather than letting Excel split columns across multiple pages. This is especially useful for wide data tables that are only a few rows tall.",
      "## Orientation matters more than people expect",
      "A wide table almost always converts more cleanly in landscape orientation than portrait, since it gives Excel more horizontal room before it needs to split columns onto a second page. Switch to landscape before converting if your data is wider than it is tall.",
      "## Checking gridlines and headers",
      "By default, Excel may not print gridlines or row/column headers, which is usually what you want for a clean, presentable PDF, but double-check the print preview beforehand if you specifically need those references visible in the final document.",
    ],
  },
  {
    slug: "convert-powerpoint-to-pdf",
    image: "/blog/convert-powerpoint-to-pdf.svg",
    title: "How to Convert PowerPoint to PDF",
    description:
      "Sharing a deck as PDF avoids font and layout issues on other people's machines. Here's how to convert it without losing your design.",
    category: "Convert",
    date: "2026-07-03",
    readTime: "3 min read",
    content: [
      "Converting a PowerPoint presentation to PDF is one of the most reliable ways to share a deck with someone, since it guarantees your slides look exactly the same on their screen as on yours, regardless of which fonts or PowerPoint version they have installed.",
      "## Why fonts are the biggest risk",
      "If your presentation uses a custom or downloaded font that isn't installed on the recipient's computer, PowerPoint will silently substitute a different font when they open the file, which can shift text boxes and break your layout. Converting to PDF locks in the exact appearance so this can never happen.",
      "## Keeping animations and transitions in mind",
      "PDF is a static format, so any animations, slide transitions, or embedded video will not carry over. Only the final visual state of each slide will convert, which is usually fine for sharing but worth knowing if your deck relies heavily on animated builds to make sense.",
      "## Choosing between slides-only and notes view",
      "Most conversion tools default to exporting just the slide content, but if you also want your speaker notes included for a version you're sharing as reading material rather than presenting live, look for a 'notes pages' or similar export option rather than the standard slide export.",
      "## File size considerations",
      "Decks with many high-resolution images or embedded video thumbnails can produce surprisingly large PDFs. If you're emailing the result, check the file size afterward and compress if needed, the same way you would with any other image-heavy PDF.",
    ],
  },
  {
    slug: "combine-word-documents-into-pdf",
    image: "/blog/combine-word-documents-into-pdf.svg",
    title: "How to Combine Multiple Word Documents Into One PDF",
    description:
      "Stitching several Word files into a single polished PDF is a common need for reports and proposals. Here's the cleanest way to do it.",
    category: "Guides",
    date: "2026-07-05",
    readTime: "4 min read",
    content: [
      "Combining several separate Word documents, like different sections of a report written by different people, into one clean final PDF is a common but slightly fiddly task if you don't have the right workflow.",
      "## Two approaches, two different results",
      "You can either convert each Word file to PDF individually and then merge the resulting PDFs together, or combine the Word documents into one file first and then convert the whole thing to PDF at once. The second approach gives you more control over consistent formatting across sections, while the first is faster when the sections were formatted independently and don't need to match exactly.",
      "## Watching out for formatting clashes",
      "When different Word documents were written by different people, they often use slightly different fonts, heading styles, or page margins. If consistency matters, it's worth standardizing these in Word before converting, since fixing formatting after everything is already a flattened PDF is far more difficult.",
      "## Getting the page order right",
      "Whichever method you use, double check the final page order carefully, especially if you're merging PDFs that were converted separately, since it's easy to combine files in the wrong sequence when you're managing several similarly-named documents at once.",
      "## Adding a consistent cover page and page numbers",
      "Once everything is combined into a single PDF, this is the right time to add a shared cover page and continuous page numbering across the whole document, rather than each section keeping its own separate numbering from when it was an individual file.",
    ],
  },
  {
    slug: "add-page-numbers-to-pdf",
    image: "/blog/add-page-numbers-to-pdf.svg",
    title: "How to Add Page Numbers to a PDF",
    description:
      "Page numbers seem trivial until you need to add them to a document that didn't have any. Here's how to do it cleanly.",
    category: "Guides",
    date: "2026-07-07",
    readTime: "3 min read",
    content: [
      "Adding page numbers to an existing PDF is a common need, especially for documents that were assembled by merging several separately-created files that each started their own numbering from one.",
      "## Choosing a starting number",
      "If your document includes a cover page or table of contents you don't want numbered, most tools let you start the visible page numbering later, say from page 3, while still counting the cover pages as part of the file. This is standard in formal reports and shouldn't be overlooked.",
      "## Placement and format options",
      "Common placements are bottom-center, bottom-right, or top-right, and common formats range from a plain number to 'Page X of Y'. Pick a placement that doesn't collide with existing footer content, and check a few pages of the actual document, not just the first one, before finalizing.",
      "## Numbering after merging documents",
      "If you merged several PDFs into one, any page numbers that were part of the original page content (printed as part of the page itself, not added by a tool) will still show their old numbering, which won't match the new combined page count. Adding fresh page numbers on top doesn't remove the old ones, so for a clean result you may need to remove old footers before adding new numbering.",
      "## Roman numerals for front matter",
      "Formal documents sometimes number front matter, like a table of contents or preface, using lowercase roman numerals before switching to standard numbers for the main content. Check whether your tool supports mixed numbering schemes if this distinction matters for your document.",
    ],
  },
  {
    slug: "add-table-of-contents-to-pdf",
    image: "/blog/add-table-of-contents-to-pdf.svg",
    title: "How to Add a Table of Contents to a PDF",
    description:
      "A long PDF without navigation is frustrating to use. Here's how to add a clickable table of contents that actually helps readers.",
    category: "Guides",
    date: "2026-07-09",
    readTime: "4 min read",
    content: [
      "A table of contents in a PDF isn't just a list of section titles on a page, the useful version is clickable, letting readers jump directly to a section instead of scrolling through dozens of pages.",
      "## Bookmarks vs. an in-page table of contents",
      "PDF bookmarks appear in the sidebar of a PDF viewer and let readers navigate the document tree, while an in-page table of contents is a regular page with clickable links, visible even when printed. The strongest documents typically have both, since bookmarks help digital readers and an in-page table of contents helps anyone flipping through a printed copy.",
      "## Building the table of contents page",
      "List each section title with its corresponding page number, and if your tool supports it, turn each entry into a clickable link that jumps to that page. Keep this list in sync manually if you edit the document afterward, since automated syncing usually only exists in the original word processor, not in a finished PDF.",
      "## Adding PDF bookmarks",
      "Most PDF editing tools let you create a bookmark for a specific page and give it a label, and organize bookmarks into nested groups matching your document's structure, like chapters and subsections. This is worth doing for any document over roughly 15-20 pages, where scrolling alone becomes tedious.",
      "## Testing navigation before sharing",
      "Click through every table of contents entry and bookmark before sending the final document, since a broken link to the wrong page is a common and easy-to-miss mistake, especially if pages were added or removed after the table of contents was first built.",
    ],
  },
  {
    slug: "crop-pdf-pages",
    image: "/blog/crop-pdf-pages.svg",
    title: "How to Crop PDF Pages",
    description:
      "Trimming excess margins or unwanted content from a PDF page is a quick fix once you know where the crop boundary actually lives.",
    category: "Guides",
    date: "2026-07-11",
    readTime: "3 min read",
    content: [
      "Cropping a PDF page removes visible margins or unwanted content around the edges without deleting anything from the underlying page content, it just changes the visible boundary.",
      "## What cropping actually does",
      "Most PDF crop tools don't delete content permanently, they adjust the page's visible boundary box while leaving the full original content technically still present underneath. This matters because it means cropping is usually reversible, unlike operations like removing pages entirely.",
      "## Cropping to remove wide margins",
      "Documents scanned with a lot of excess white space around the edges are a common reason to crop, especially when the original was designed for a larger page size than the content actually needs. Cropping tightens the visible area to just the content, making it look more intentional when read on screen.",
      "## Cropping consistently across pages",
      "If you're cropping a multi-page document, apply the same crop margins to every page rather than cropping page by page, unless individual pages genuinely need different amounts trimmed. Most tools let you set one crop boundary and apply it to the whole document at once.",
      "## Cropping vs. resizing",
      "Cropping only removes visible edges, it doesn't change the underlying page dimensions the way resizing does. If your goal is actually to make the whole page a different size, like fitting A4 content onto Letter paper, you want a resize operation instead of a crop.",
    ],
  },
  {
    slug: "resize-pdf-pages",
    image: "/blog/resize-pdf-pages.svg",
    title: "How to Resize PDF Pages",
    description:
      "Fitting a document made for one paper size onto another without cutting off content takes more than a simple scale. Here's how it works.",
    category: "Guides",
    date: "2026-07-13",
    readTime: "3 min read",
    content: [
      "Resizing a PDF changes the actual page dimensions, which is different from zooming in a viewer or cropping visible margins. It's most often needed when a document made for one paper standard, like US Letter, needs to be usable on another, like A4.",
      "## Letter vs. A4: the core problem",
      "US Letter (8.5 x 11 inches) and A4 (8.27 x 11.69 inches) have different proportions, not just different sizes, so a direct resize without adjustment can either cut off content at the bottom or leave odd empty margins. Understanding this mismatch upfront prevents a lot of confusion about why a 'resized' document still looks slightly off.",
      "## Scaling vs. reformatting",
      "A straightforward resize scales the entire page content uniformly to fit the new dimensions, which works well for most documents but can make text slightly larger or smaller than expected. True reformatting, adjusting margins and layout to specifically suit the new page size, produces a cleaner result but generally isn't something a simple PDF resize tool does automatically.",
      "## Checking margins after resizing",
      "After resizing, check that no text or important content got pushed too close to the new page edges, since printers typically can't print all the way to the edge of a physical page and will clip anything positioned too close to the border.",
      "## When to resize vs. start over",
      "For a document you'll need in multiple paper sizes going forward, it's often worth setting up the original source file, like the Word or InDesign document, with a layout that adapts to different sizes, rather than relying on repeatedly resizing a finished PDF each time.",
    ],
  },
  {
    slug: "redact-sensitive-information-pdf",
    image: "/blog/redact-sensitive-information-pdf.svg",
    title: "How to Redact Sensitive Information in a PDF",
    description:
      "A black box drawn over text isn't real redaction, and it's a more common mistake than people realize. Here's how to redact properly.",
    category: "Security",
    date: "2026-07-15",
    readTime: "5 min read",
    content: [
      "Redaction has a genuinely dangerous failure mode: simply drawing a black rectangle over sensitive text in a PDF editor often leaves the original text fully intact underneath, selectable and copyable the moment someone selects it or copies the page into another program.",
      "## Why 'covering' text isn't redaction",
      "A black box placed on top of text is just another visual element layered over the page, it doesn't remove or alter the underlying text data at all. Anyone who copies the 'redacted' paragraph and pastes it elsewhere, or opens the file in a different viewer that renders layers differently, can potentially recover the original text.",
      "## What real redaction requires",
      "Proper redaction actually deletes the underlying text and any associated image data in the selected area, permanently replacing it, not just visually hiding it. A genuine redaction tool will explicitly say it removes the content, not just draws over it, and this distinction is the single most important thing to check before trusting any redaction tool with sensitive information.",
      "## Redacting images and metadata too",
      "Sensitive information can hide in more than just visible text: image content (like a photo of a document containing details you want removed) and file metadata (like author names or hidden comments) both need separate attention. A thorough redaction pass checks all three: visible text, images, and metadata.",
      "## Verifying the redaction worked",
      "After redacting, try selecting text in the area you redacted, if you can still highlight and copy the underlying words, the redaction failed and the sensitive content is still there, just visually hidden. Always verify with this simple test before sharing a redacted document, especially for anything legally or professionally sensitive.",
    ],
  },
  {
    slug: "flatten-pdf-form",
    image: "/blog/flatten-pdf-form.svg",
    title: "How to Flatten a PDF Form",
    description:
      "Flattening locks a filled-out form so it can't be accidentally edited again. Here's what it does and when you actually need it.",
    category: "Guides",
    date: "2026-07-17",
    readTime: "3 min read",
    content: [
      "Flattening a PDF form converts interactive, fillable form fields into permanent, non-editable content, essentially freezing whatever was entered into those fields so they behave like regular static text on the page from then on.",
      "## Why you'd want to flatten a form",
      "Once a form has been filled out and is ready to submit, share, or archive, flattening it prevents the recipient (or you, accidentally) from changing the entered answers later. It also improves compatibility, since some PDF viewers don't render fillable form fields consistently, but they all render flattened static content the same way.",
      "## What happens to the data during flattening",
      "The values entered into each field get 'baked' into the page as regular text or graphics, permanently replacing the interactive field. This is a one-way operation: once flattened, the form fields are gone, and you can't go back and edit individual answers the way you could before flattening, short of manually editing the text like any other PDF content.",
      "## When not to flatten yet",
      "If a form still needs additional people to fill in more fields, like a multi-signer approval form, don't flatten it until everyone is done, since flattening removes the very fields the next person would need to fill in.",
      "## Flattening as part of archiving",
      "Flattening is a common last step before archiving completed forms long-term, since a flattened PDF is simpler, more universally compatible, and immune to any accidental edits to what should be a finalized historical record.",
    ],
  },
  {
    slug: "compare-two-pdf-files",
    image: "/blog/compare-two-pdf-files.svg",
    title: "How to Compare Two PDF Files for Differences",
    description:
      "Manually eyeballing two versions of a contract for changes is slow and unreliable. Here's how PDF comparison actually catches what changed.",
    category: "Comparisons",
    date: "2026-07-19",
    readTime: "4 min read",
    content: [
      "Comparing two versions of a PDF, like an original contract and a revised draft, by eye is slow and genuinely unreliable, since small but important changes, like a single digit in a price, are easy to miss when scanning by hand.",
      "## Text comparison vs. visual comparison",
      "A text-based comparison extracts and compares the actual text content of both files, flagging additions, deletions, and changes, similar to how tracked changes work in a word processor. A visual comparison instead overlays the two pages as images and highlights pixel differences, which is more useful for documents where formatting or layout changes matter as much as the text itself.",
      "## When text comparison isn't enough",
      "If your document is a scanned PDF with no real text layer, a text-based comparison tool has nothing to compare, since there's no extractable text at all. In that case, you either need to run OCR on both files first, or use a visual comparison tool that works directly with the page images.",
      "## Reading a comparison report",
      "A good comparison tool doesn't just tell you that something changed, it shows you exactly what, usually with additions and deletions marked in different colors, similar to a code diff. Skim the full report rather than only the summary, since summaries sometimes group multiple distinct changes into one vague count.",
      "## A practical use case",
      "Comparing PDF versions is especially valuable for contracts and legal documents going through several rounds of negotiation, where confirming that only the agreed-upon changes were made, and nothing else was altered, actually matters.",
    ],
  },
  {
    slug: "print-pdf-correctly",
    image: "/blog/print-pdf-correctly.svg",
    title: "How to Print a PDF Correctly (Without Cut-Off Margins)",
    description:
      "PDFs that look perfect on screen sometimes print with cropped edges or the wrong scale. Here's how to avoid that.",
    category: "Troubleshooting",
    date: "2026-07-21",
    readTime: "4 min read",
    content: [
      "A PDF that displays perfectly on screen can still come out of a printer with cut-off edges, shrunken content, or the wrong paper size entirely, and the cause is almost always in the print dialog settings, not the PDF itself.",
      "## The 'Fit to Page' trap",
      "Print dialogs commonly default to a 'Fit to Printable Area' or similar scaling option, which can slightly shrink or shift your content to accommodate the printer's unprintable margin, even when your document was already correctly sized. If your PDF is being printed at exactly its intended size, choose 'Actual Size' or '100%' instead of a fit-to-page option.",
      "## Matching paper size in the print dialog",
      "If your PDF was made for A4 but your print dialog defaults to Letter (or vice versa), content near the bottom or right edge can get cut off even though nothing is wrong with the file. Always double check the paper size selected in the print dialog matches what the document was actually designed for.",
      "## Printer margins vs. page content",
      "Nearly all printers have a small unprintable margin around the physical edge of the paper, typically a few millimeters, that no amount of software setting can override, since it's a hardware limitation of the printer itself. If your PDF has content placed extremely close to the page edge, it may always be at risk of minor clipping regardless of settings.",
      "## Checking print preview before committing",
      "Nearly every print dialog offers a preview showing exactly how the page will look once printed, including where it will be scaled or cropped. Always check this preview, especially for documents with tight margins or full-bleed images, rather than trusting the on-screen PDF view alone.",
    ],
  },
  {
    slug: "resize-pdf-to-a4",
    image: "/blog/resize-pdf-to-a4.svg",
    title: "How to Resize a PDF to A4",
    description:
      "US Letter and A4 aren't the same shape, not just the same size. Here's how to convert one to the other without losing content.",
    category: "Guides",
    date: "2026-07-23",
    readTime: "3 min read",
    content: [
      "Converting a US Letter PDF to A4, or the reverse, comes up constantly for anyone sharing documents internationally, since the US almost exclusively uses Letter while most of the rest of the world uses A4.",
      "## The core size difference",
      "US Letter is 8.5 x 11 inches, while A4 is 8.27 x 11.69 inches, meaning A4 is slightly narrower and noticeably taller. Because the proportions differ, not just the total area, a naive resize can leave a strip of empty space at the bottom or cut off a small amount of content at the edge.",
      "## Choosing scale vs. crop-and-pad",
      "A scaling resize shrinks or stretches the entire page proportionally to fit the new dimensions, which keeps everything visible but can slightly alter margins and spacing. An alternative approach centers the original content and adds or trims blank margin space to fit the new page shape, which better preserves the original layout's exact proportions at the cost of extra white space.",
      "## Checking your margins after resizing",
      "After converting, always check the margins on both the top/bottom and left/right edges of the resized document, since the size difference between Letter and A4 tends to show up most in vertical spacing rather than horizontal.",
      "## Preventing this next time",
      "If you regularly send documents internationally, setting your source document (in Word, Google Docs, or similar) to A4 from the start avoids needing to resize the PDF after the fact, and produces a cleaner result than any after-the-fact conversion.",
    ],
  },
  {
    slug: "convert-html-to-pdf",
    image: "/blog/convert-html-to-pdf.svg",
    title: "How to Convert HTML to PDF",
    description:
      "Turning a web page into a clean PDF sounds simple but layouts, fonts, and interactive elements can all break in the process. Here's how to do it well.",
    category: "Convert",
    date: "2026-07-25",
    readTime: "4 min read",
    content: [
      "Converting a web page or HTML document into a PDF is useful for archiving articles, saving receipts, or turning a web-based report into something shareable and fixed, but web layouts don't always translate cleanly to a printed page format.",
      "## Why some pages convert cleanly and others don't",
      "Pages built with simple, print-friendly layouts convert well, while pages relying heavily on complex CSS grids, fixed-position elements, or JavaScript-rendered content can come out with broken layouts, missing content, or elements overlapping in the PDF. Sites with a lot of ads or navigation clutter also tend to carry that clutter straight into the PDF unless the tool specifically filters it out.",
      "## Using a browser's built-in print-to-PDF",
      "Most modern browsers can save any page as a PDF directly through the print dialog, which is often the fastest option and tends to respect the page's own print stylesheet if the site has one. This is usually the best starting point before reaching for a dedicated conversion tool.",
      "## Handling pages behind a login or paywall",
      "Standalone HTML-to-PDF tools that take just a URL generally can't access pages that require you to be logged in, since they don't have your session or credentials. For those pages, using your own browser's print-to-PDF while logged in is the more reliable option.",
      "## Preserving links",
      "A well-converted HTML-to-PDF file keeps hyperlinks clickable in the resulting PDF, not just visually styled as blue underlined text. If clickable links matter for your use case, test a few after converting to confirm they still work.",
    ],
  },
  {
    slug: "convert-pdf-to-html",
    image: "/blog/convert-pdf-to-html.svg",
    title: "How to Convert PDF to HTML",
    description:
      "Turning a PDF into a web page is useful for publishing content online, but the layout rarely survives the trip unchanged. Here's what to expect.",
    category: "Convert",
    date: "2026-07-27",
    readTime: "4 min read",
    content: [
      "Converting a PDF to HTML is the reverse of the more common HTML-to-PDF direction, and it's generally the more difficult conversion, since PDF is a fixed-layout format and HTML is meant to reflow and adapt to different screen sizes.",
      "## Why the layout often doesn't survive intact",
      "A PDF positions text and images at exact coordinates on a fixed page. HTML, especially responsive HTML meant to work on both phones and desktops, doesn't work that way at all. A converter has to make judgment calls about which parts of the original fixed layout to preserve and which to let reflow, and it doesn't always guess right, particularly with multi-column layouts or heavily designed pages.",
      "## What converts well",
      "Simple, mostly text-based PDFs with a straightforward single-column layout, like a basic report or article, tend to convert to reasonably clean HTML. Complex brochures, infographics, or anything with overlapping text and graphics convert far less predictably.",
      "## Cleaning up after conversion",
      "Expect to do some manual cleanup after converting, particularly around image placement, heading structure, and any tables. Treat the conversion output as a solid first draft rather than a finished, publish-ready web page.",
      "## When to just rebuild instead",
      "For an important document that needs to become a genuinely good web page, like a long report you're publishing as a blog post, it's often faster in the long run to manually rebuild it in HTML using the PDF as a reference, rather than trying to get an automated conversion to look exactly right.",
    ],
  },
  {
    slug: "pdf-a-archiving-guide",
    image: "/blog/pdf-a-archiving-guide.svg",
    title: "PDF/A Explained: How to Archive PDFs for the Long Term",
    description:
      "A regular PDF isn't actually guaranteed to open the same way in twenty years. Here's what PDF/A is and when you actually need it.",
    category: "Productivity",
    date: "2026-07-29",
    readTime: "4 min read",
    content: [
      "Most people assume any PDF will simply open forever, but a standard PDF can technically rely on things like external fonts, embedded video, encryption, or JavaScript that may not be supported the same way by future software. PDF/A exists specifically to solve that long-term reliability problem.",
      "## What makes PDF/A different",
      "PDF/A is a stricter subset of the regular PDF format, specifically designed for long-term archiving. It requires all fonts to be embedded directly in the file (so nothing depends on fonts being installed on a future device), disallows JavaScript and external content links, and disallows encryption, all specifically to guarantee the document will render identically decades from now.",
      "## Who actually needs PDF/A",
      "Everyday documents, like a resume or an invoice you're sending this week, don't need PDF/A. It matters for legal records, government filings, medical records, and institutional archives, anything that must remain readable and unchanged for years or decades and may be subject to compliance requirements.",
      "## Converting an existing PDF to PDF/A",
      "Most PDF/A conversion tools will check your file for anything that violates the PDF/A standard, like missing embedded fonts or JavaScript, and either fix it automatically or flag it for you to address manually before the conversion can complete.",
      "## A common misconception",
      "PDF/A is not a different-looking file or a special reader, a PDF/A file opens and displays exactly like a normal PDF in any standard PDF viewer, the difference is entirely in what's technically permitted inside the file to guarantee long-term compatibility.",
    ],
  },
  {
    slug: "scanned-photos-to-searchable-pdf",
    image: "/blog/scanned-photos-to-searchable-pdf.svg",
    title: "How to Turn Scanned Photos Into a Searchable PDF",
    description:
      "A pile of scanned document photos isn't useful until you can actually search it. Here's how to build a searchable archive properly.",
    category: "Guides",
    date: "2026-07-31",
    readTime: "5 min read",
    content: [
      "Scanning a stack of paperwork into PDF is only half the job. Without OCR, that scanned PDF is just a set of page images, meaning you can't search for a specific word, invoice number, or name anywhere inside it, which defeats much of the point of digitizing paperwork in the first place.",
      "## Combining scanning and OCR into one workflow",
      "The most efficient approach is to combine multiple scanned photos into a single PDF first, then run OCR across the whole document in one pass, rather than OCR-ing each photo individually before combining them. This keeps the workflow simple and ensures consistent text recognition settings across every page.",
      "## Preparing photos for the best OCR results",
      "Before combining and running OCR, straighten and crop each photo so the document fills the frame with minimal background, and make sure lighting is even without harsh shadows across the text. Cleaner input photos translate directly into more accurate OCR output.",
      "## Making the archive genuinely searchable",
      "A properly OCR'd PDF keeps the original scanned page images visible while adding an invisible text layer underneath, so the document still looks exactly like the original scan but can be searched, copied from, and indexed by tools like your operating system's file search.",
      "## Organizing a growing searchable archive",
      "Once individual documents are searchable, naming and folder structure become less critical for finding things, since you can search by content instead of relying purely on filenames. Still, a basic consistent naming and folder system remains worth keeping for browsing and backup purposes.",
    ],
  },
  {
    slug: "add-bookmarks-to-pdf",
    image: "/blog/add-bookmarks-to-pdf.svg",
    title: "How to Add Bookmarks to a PDF",
    description:
      "PDF bookmarks are the sidebar navigation most long documents are missing. Here's how to add them so readers can actually find their way around.",
    category: "Guides",
    date: "2026-08-02",
    readTime: "3 min read",
    content: [
      "PDF bookmarks show up as a collapsible navigation tree in the sidebar of most PDF viewers, letting readers jump directly to a chapter or section instead of scrolling through the entire document to find what they need.",
      "## When bookmarks are worth adding",
      "Any document over roughly 15-20 pages with distinct sections, like a report, manual, or long proposal, benefits from bookmarks. Short documents rarely need them, since scrolling through a five-page PDF isn't a real burden the way scrolling through an eighty-page one is.",
      "## Creating a bookmark",
      "In most PDF editors, you navigate to the exact page and position you want to link to, then create a new bookmark and give it a clear, descriptive label, ideally matching the actual heading text on that page so readers aren't confused by mismatched labels.",
      "## Organizing bookmarks into a hierarchy",
      "For documents with subsections, nest bookmarks under their parent chapter rather than listing everything as one long flat list. Most tools support drag-and-drop nesting in the bookmark panel, letting you build a structure that mirrors your document's actual outline.",
      "## Bookmarks vs. an in-document table of contents",
      "Bookmarks only help readers viewing the file digitally, since they don't appear when printed. For documents that might also be printed, pair bookmarks with an actual table of contents page as well, so navigation works both on screen and on paper.",
    ],
  },
  {
    slug: "insert-blank-page-into-pdf",
    image: "/blog/insert-blank-page-into-pdf.svg",
    title: "How to Insert a Blank Page Into a PDF",
    description:
      "Sometimes you need an empty page for notes, a divider, or print pagination. Here's the quickest way to add one.",
    category: "Guides",
    date: "2026-08-04",
    readTime: "2 min read",
    content: [
      "Inserting a blank page into an existing PDF is a small but common need, whether it's for a notes page, a section divider, or simply to force a document to end on an even page number for double-sided printing.",
      "## Choosing where to insert it",
      "Decide whether the blank page goes before or after a specific existing page, and double-check the page count of your document beforehand so you're inserting at the position you actually intend, especially in a long document where miscounting by one page is an easy mistake.",
      "## Matching the page size",
      "Make sure the inserted blank page matches the page size of the surrounding document, an A4 document with an accidentally inserted Letter-sized blank page will look inconsistent and may cause printing issues. Most insertion tools handle this automatically by matching the adjacent page, but it's worth confirming.",
      "## Blank pages for double-sided printing",
      "If your document will be printed double-sided and needs new sections to always start on a right-hand (odd-numbered) page, inserting a blank page before certain sections is a standard way to force that alignment, the same technique used in professionally printed books.",
      "## Removing it later",
      "If you added a blank page temporarily, remember it's just a regular page as far as the PDF is concerned, removing it later uses the same page-removal process as deleting any other page from the document.",
    ],
  },
  {
    slug: "recover-text-from-corrupted-pdf",
    image: "/blog/recover-text-from-corrupted-pdf.svg",
    title: "How to Recover Text From a Corrupted PDF",
    description:
      "A corrupted PDF isn't always a total loss. Here's what recovery actually involves and when it's realistic to expect success.",
    category: "Troubleshooting",
    date: "2026-08-06",
    readTime: "4 min read",
    content: [
      "A corrupted PDF, one that won't open normally or throws a 'damaged file' error, isn't necessarily unrecoverable, but success depends heavily on what specifically went wrong and how badly the file's internal structure was affected.",
      "## What usually causes corruption",
      "The most common causes are an interrupted download or file transfer, a crash during saving, or a storage device error while the file was being written. Understanding the cause matters because a partially-downloaded file is a very different repair problem than one damaged by a failing hard drive.",
      "## Trying a repair tool first",
      "PDF repair tools work by scanning the file's internal structure for whatever valid data remains and attempting to rebuild a working document around it. This works reasonably well for files with minor structural damage but often can't fully recover files that are missing large chunks of data entirely.",
      "## When repair only gets you partial content",
      "Sometimes a repair tool can recover some pages or some text but not everything, in which case exporting whatever it does successfully extract as a partial PDF or plain text file is a reasonable fallback, even if it's not the complete original document.",
      "## Preventing this in the future",
      "Keep an unmodified backup of important documents separate from your working copy, and avoid saving over a file mid-transfer or mid-download. For anything genuinely important, a small amount of backup discipline avoids the far more time-consuming process of trying to recover a corrupted file after the fact.",
    ],
  },
];

export function getAllPosts(): BlogPost[] {
  return [...blogPosts].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}

export function getAllSlugs(): string[] {
  return blogPosts.map((post) => post.slug);
}
