export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  date: string;
  readTime: string;
  image: string;
  content: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "merge-pdf-without-losing-quality",
    image: "/blog/merge-pdf-without-losing-quality.svg",
    title: "How to Merge PDF Files Without Losing Quality",
    description:
      "Combining PDFs is easy, but it's just as easy to end up with a bloated or blurry file if you use the wrong method. Here's how to do it right.",
    category: "Guides",
    date: "2026-05-02",
    readTime: "5 min read",
    content: [
      "I've merged enough PDFs to know the failure mode: you combine three clean documents, open the result, and somehow the text looks worse than any of the originals. That's not bad luck — it's the tool.",
      "## Why merging can quietly ruin quality",
      "A lot of merge tools don't actually copy your pages, they re-render them. That means every page gets flattened into an image and recompressed behind the scenes, even the ones that were sharp vector text to begin with. It's faster to build software that way, but it's why a 'merged' file can look noticeably worse than what you started with.",
      "A tool built properly just copies the underlying PDF objects and stitches them together — no re-encoding, no flattening. Fonts stay fonts. Images stay at their original resolution.",
      "## The actual steps",
      "Get your source files into the shape you want first — merging can't add detail that isn't there. Upload them (order doesn't matter if your tool supports drag-and-drop reordering), run the merge, and actually open the result and zoom to 100% on a few pages. Don't just glance at the thumbnail.",
      "## If the merged file is too big",
      "Compress after merging, never before. Compressing first means you're merging already-degraded files, and there's no getting that detail back. Merge first, then compress the combined file if size is genuinely a problem.",
      "## Bottom line",
      "Keep sources at full quality, get the page order right, check the output at real zoom before you send it anywhere, and only compress if you actually need to. That order avoids both complaints people have about merged PDFs — blurry pages and files that are way bigger than they should be.",
    ],
  },
  {
    slug: "reduce-pdf-file-size-without-losing-quality",
    image: "/blog/reduce-pdf-file-size-without-losing-quality.svg",
    title: "How to Reduce PDF File Size Without Losing Quality",
    description:
      "Large PDFs bounce off email attachment limits and slow down uploads. Here's what actually shrinks a file size without turning your pages to mush.",
    category: "Guides",
    date: "2026-05-05",
    readTime: "6 min read",
    content: [
      "A ten-page contract with no images might be 200KB. A ten-page scan of that same contract, photographed instead of exported, can hit 40MB. Almost all of that weight is images, not text — which is the key to compressing smartly instead of just cranking a slider and hoping.",
      "## What's actually happening during compression",
      "Two things, mostly: images get downsampled to a lower resolution, and whatever's left gets compressed harder. Text and vector graphics are usually left alone entirely, since they barely take up space to begin with.",
      "## Picking a compression level",
      "Light compression is plenty for anything that'll only be read on a screen — most monitors can't even show more detail than a 150 DPI image gives you. Medium is a safe default for general sharing. High is for situations where size matters more than anything else and you don't need to print it, because it will visibly soften photos and scanned text.",
      "## Scanned documents specifically",
      "Scanners default to 300 or 600 DPI more often than not, which is way more than you need for reading on a screen. A compressor built for scans specifically can often cut 80% off the file size with barely any visible difference.",
      "## What not to do",
      "Don't run the same file through compression twice. Each pass re-compresses already-lossy images, and the damage stacks. If a compressed file is still too big, go back to the original and try a stronger setting from scratch — don't compress the compressed version.",
      "## A number to aim for",
      "Most email providers cap you around 25MB, and plenty of upload forms are stricter than that. Know your target size before you start rather than compressing three times by trial and error.",
    ],
  },
  {
    slug: "convert-pdf-to-word",
    image: "/blog/convert-pdf-to-word.svg",
    title: "How to Convert a PDF to a Word Document",
    description:
      "Converting a PDF to Word works well for some documents and badly for others. Here's how to get an editable result that doesn't fall apart.",
    category: "Guides",
    date: "2026-05-08",
    readTime: "5 min read",
    content: [
      "PDF to Word conversion has a bad reputation, and honestly, it's only half deserved. Whether it works well comes down almost entirely to how the PDF was made in the first place.",
      "## Why some conversions come out perfect and others don't",
      "A PDF exported from Word or Google Docs already has structured text inside it, so converting it back is nearly a clean reversal. A PDF that started life as a scanned image has no real text at all — just a picture of text — so the converter has to guess at every word using OCR, and guessing means mistakes.",
      "## A clean conversion from a text-based PDF",
      "Upload it, run the conversion, then check paragraph spacing, bullets, and tables came through right. Complex multi-column layouts are the most likely thing to shift, since Word doesn't handle absolutely-positioned text the same way a PDF does.",
      "## A usable conversion from a scanned PDF",
      "Look for a converter that explicitly runs OCR rather than one that just pulls whatever text metadata exists — scanned pages usually have none. Afterward, proofread carefully. Numbers and dates are exactly where OCR mistakes like to hide.",
      "## What tends to break",
      "Headers, footers, footnotes, and text wrapped around images are the usual suspects for needing manual cleanup. Budget a few minutes for that rather than expecting a perfect one-click result.",
      "## When it's not even worth converting",
      "If you only need a paragraph or two, just open the PDF, select the text, and paste it into Word. Save full conversion for when you actually need to substantially edit or reformat the whole thing.",
    ],
  },
  {
    slug: "split-pdf-into-multiple-files",
    image: "/blog/split-pdf-into-multiple-files.svg",
    title: "How to Split a PDF Into Multiple Files",
    description:
      "Whether you need one page pulled out or a large document broken into chapters, here's how PDF splitting actually works.",
    category: "Guides",
    date: "2026-05-11",
    readTime: "4 min read",
    content: [
      "Splitting is one of the simpler things you can do to a PDF, but there's more than one way to do it depending on what you actually need out the other end.",
      "## Splitting by page range",
      "Need pages 5 through 10 of a report? A range split does exactly that — you set start and end, the tool extracts that chunk as a new file, and the original stays untouched.",
      "## Splitting into individual pages",
      "If every page needs to become its own file — say, a scanned batch of receipts becoming one file per receipt — look for a 'split all pages' option instead of extracting ranges one at a time.",
      "## Splitting by size or page count",
      "Some tools will chop a large document into equal-ish chunks, which is handy when you need to stay under a size limit and don't care exactly where the cuts fall.",
      "## Keeping track of the output",
      "Splitting into a dozen files gets messy fast. Most tools auto-number the outputs by page range, which is genuinely more useful than generic names — you can tell at a glance which pages ended up where.",
      "## The mistake people actually make",
      "Splitting a file, editing one piece, then merging it back in — and the page order gets scrambled. Always double-check order after re-merging, especially if pieces got renamed or reordered along the way.",
    ],
  },
  {
    slug: "password-protect-pdf",
    image: "/blog/password-protect-pdf.svg",
    title: "How to Password Protect a PDF",
    description:
      "PDF passwords come in two very different types, and using the wrong one gives you a false sense of security. Here's the difference.",
    category: "Security",
    date: "2026-05-14",
    readTime: "5 min read",
    content: [
      "PDF password protection isn't one feature — it's two — and mixing them up is the most common mistake people make trying to secure a document.",
      "## Open password vs. permissions password",
      "An open (user) password stops anyone from opening the file at all until they enter it. A permissions (owner) password lets the file open but restricts what can be done with it — printing, copying, editing. If you actually want the contents kept confidential, you need the open password, full stop.",
      "## Picking a password that holds up",
      "A short password feels secure but isn't — PDF encryption, especially older versions, is crackable with brute force. Go 12+ characters, mix letters, numbers, symbols, and skip anything tied to the document itself, like a company name or the year.",
      "## Restricting permissions separately",
      "Beyond the password, most tools let you turn off printing, copying, or editing independently. Useful for discouraging casual copy-paste of a contract, but don't treat it as real security — permissions restrictions are far easier to bypass than a genuine open password.",
      "## Sharing it safely",
      "Never send the password in the same email as the file. Send the file, then the password through a different channel — text, a call, whatever — so intercepting one doesn't hand over both.",
      "## Getting it off later",
      "You'll need the original password to remove it. There's no legitimate way around a PDF password you don't know — that's the entire point of it existing — so keep your passwords somewhere you won't lose them.",
    ],
  },
  {
    slug: "remove-password-from-pdf",
    image: "/blog/remove-password-from-pdf.svg",
    title: "How to Remove a Password From a PDF",
    description:
      "If you own the file and know the password, removing it is quick. Here's how it works and what to watch out for.",
    category: "Security",
    date: "2026-05-16",
    readTime: "3 min read",
    content: [
      "Removing a password from a file you legitimately own comes up more than you'd think — usually because the file's already sitting somewhere secure and the extra password step has turned into an annoyance rather than a protection.",
      "## What you'll need first",
      "The current password. A removal tool decrypts using the password you give it — it doesn't crack or guess anything. Genuinely forgotten your password? That's a different, much harder problem, and legitimate tools won't help you bypass one you don't know.",
      "## How the removal actually works",
      "Upload the file, enter the password, get back a new copy with no password requirement. The original stays exactly as it was, so if something goes wrong you can try again.",
      "## A note on permissions-only restrictions",
      "If the file just has printing or editing restrictions (owner password, not a real lock), some tools can strip those even without the original password, since the file itself isn't locked — only certain actions are limited. That's a legal gray area depending on why the restriction exists, so only do this on documents you actually have rights to modify.",
      "## Keep a backup",
      "Before removing protection from anything important, keep a copy of the protected original — in case you need it again for archival or compliance reasons down the line.",
    ],
  },
  {
    slug: "convert-image-to-pdf",
    image: "/blog/convert-image-to-pdf.svg",
    title: "How to Convert Images to PDF",
    description:
      "Turning JPGs or PNGs into a PDF is useful for everything from scanned receipts to portfolios. Here's how to do it cleanly.",
    category: "Guides",
    date: "2026-05-19",
    readTime: "4 min read",
    content: [
      "Turning images into a PDF is one of the most common reasons people show up to a PDF tool — usually to combine a bunch of photos of a document, like a contract shot page by page on a phone, into one shareable file.",
      "## Getting the order right",
      "Upload a batch of images and most tools sort them alphabetically by filename, which almost never matches the order you actually photographed them in. Rename with a number prefix first (01, 02, 03...) or use a tool that lets you drag to reorder before generating the file.",
      "## Matching page size to content",
      "Photos of documents usually look best on a standard page size like A4 or Letter, so the result prints and displays the way people expect. Photos meant to be viewed as images — a portfolio, say — often look better matching the photo's own aspect ratio instead.",
      "## Better photos, better results",
      "Shoot in good, even light, and hold the camera as directly overhead as you can — angled shots distort text and make it harder to read. Auto-crop or auto-straighten features can patch minor issues, but a clean photo to start with saves you a step later.",
      "## One image per page, or a grid",
      "Most tools default to one image per page. Want two smaller images — receipts, say — sharing a page? Check whether your tool has a grid layout option, since not all of them do.",
    ],
  },
  {
    slug: "convert-pdf-to-jpg-png",
    image: "/blog/convert-pdf-to-jpg-png.svg",
    title: "How to Convert PDF Pages to JPG or PNG",
    description:
      "Sometimes you need an image, not a document. Here's how PDF-to-image conversion works and which format to pick.",
    category: "Guides",
    date: "2026-05-22",
    readTime: "3 min read",
    content: [
      "Sometimes a PDF just isn't the right format — you need to drop a page into a slideshow, a website, or a social post, and none of those want a PDF.",
      "## JPG or PNG?",
      "JPG wins for pages with photos or complex color — it compresses well and keeps files small. PNG wins for mostly-text pages, diagrams, or line art, since it doesn't introduce the blurring JPG gets around sharp edges and text.",
      "## Picking a resolution",
      "Low resolution is fine for on-screen viewing but turns pixelated fast if printed or zoomed. Any chance it'll be printed or shown large? Export higher, even if the file's bigger.",
      "## Multi-page documents",
      "Most converters let you turn every page into its own image file (usually delivered as a zip) or just the pages you pick. Decide which one you need up front — re-running the whole thing for one missed page is an annoying extra step.",
      "## What you lose in the conversion",
      "Once it's an image, any selectable text, links, or form fields are gone — it's just a picture now. Need the recipient to search or copy text? Keep the PDF, or send both.",
    ],
  },
  {
    slug: "add-digital-signature-to-pdf",
    image: "/blog/add-digital-signature-to-pdf.svg",
    title: "How to Add a Digital Signature to a PDF",
    description:
      "Not all electronic signatures are equal. Here's the difference between a drawn signature and a cryptographic digital signature, and when you need each.",
    category: "Security",
    date: "2026-05-25",
    readTime: "5 min read",
    content: [
      "'Digital signature' actually covers two pretty different things, and knowing which one you need matters more than most people realize.",
      "## Electronic signature vs. a real digital signature",
      "An electronic signature is typically a drawn, typed, or uploaded image of your signature dropped onto the page. Fast, and fine for most everyday paperwork — but it doesn't cryptographically prove who signed or that the file hasn't been touched since. A true digital signature uses a certificate-based key that does both, and that's what's required for legal, government, or high-stakes business documents.",
      "## Adding a simple one",
      "Upload the PDF, draw your signature with a mouse or trackpad, type your name in a script font, or upload a photo of your handwritten signature. Place it, save it. Fine for informal agreements and internal approvals.",
      "## Adding a certificate-based one",
      "This needs an actual digital certificate — from a certificate authority or generated in signing software — and produces something that verifies cryptographically and flags a warning in PDF readers if the document changes after signing. That's the one you want for contracts and legal filings.",
      "## When several people need to sign",
      "Decide upfront whether signers go in order or all at once — some documents genuinely need sequential signing, others don't. And track which version each signer is working from, so signatures don't end up on an outdated copy.",
    ],
  },
  {
    slug: "rotate-pages-in-pdf",
    image: "/blog/rotate-pages-in-pdf.svg",
    title: "How to Rotate Pages in a PDF",
    description:
      "A sideways scan is a small annoyance with a quick fix. Here's how to rotate one page or an entire document.",
    category: "Guides",
    date: "2026-05-28",
    readTime: "3 min read",
    content: [
      "Sideways or upside-down pages are one of the most common tiny annoyances in PDFs, usually caused by a scanner that fed a sheet in wrong.",
      "## The whole document at once",
      "If every page came out rotated the same way — common with scanned batches — use a 'rotate all pages' option and fix the whole file in one step instead of page by page.",
      "## Individual pages only",
      "Mixed orientation shows up a lot in scans that combine portrait pages with landscape tables or charts. Most tools let you pick specific pages and rotate just those.",
      "## 90, 180, or 270",
      "Sideways needs a 90° turn one way or the other. Upside-down needs a full 180°. Not sure which direction? Rotate 90° and check the preview before saving — guess wrong and it's just sideways the other way.",
      "## Making it stick",
      "Some viewers rotate a page for display only, and it resets the next time the file opens rather than actually saving into the file. Make sure your tool permanently applies the rotation if you're sharing it with anyone else.",
    ],
  },
  {
    slug: "remove-pages-from-pdf",
    image: "/blog/remove-pages-from-pdf.svg",
    title: "How to Remove Pages From a PDF",
    description:
      "Deleting a blank page or an outdated section shouldn't require rebuilding the whole document. Here's the fast way.",
    category: "Guides",
    date: "2026-05-30",
    readTime: "3 min read",
    content: [
      "Deleting pages from a PDF is common cleanup work — a blank scanned page, an outdated appendix, a cover sheet that no longer applies.",
      "## Picking the pages to remove",
      "A tool that shows thumbnail previews and lets you click to select is far more reliable than typing page numbers. It's easy to miscount in a long document, especially when printed page numbers don't line up with the PDF's actual page order.",
      "## Removing scattered pages",
      "Need to drop pages 3, 7, and 12 but keep everything else? Look for a tool that takes multiple individual selections instead of only a single continuous range, or you'll be doing several passes.",
      "## What happens to printed page numbers",
      "Removing pages doesn't touch any page numbers printed as part of the content itself — those are just text on the page, not a PDF property. For formal documents, you may need a separate step to fix them afterward.",
      "## Check before you finalize",
      "Always preview the result, especially for contracts or reports, where an accidentally removed page changes meaning, not just length.",
    ],
  },
  {
    slug: "extract-pages-from-pdf",
    image: "/blog/extract-pages-from-pdf.svg",
    title: "How to Extract Pages From a PDF",
    description:
      "Need just a few pages out of a much longer document? Here's how extraction differs from splitting or deleting.",
    category: "Guides",
    date: "2026-06-02",
    readTime: "3 min read",
    content: [
      "Extraction is basically the mirror of removal: instead of deleting what you don't want, you pull out just what you do want and save it separately, leaving the original untouched.",
      "## Extract vs. split",
      "Splitting usually means breaking a whole document into complete pieces. Extraction is more targeted — you just want pages 4 and 9 out of a 40-page report and don't care what happens to the rest.",
      "## One range, or scattered pages",
      "Consecutive pages? A simple start-and-end range works. Non-consecutive — page 2, page 15, page 30? Make sure your tool supports picking individual pages in one go rather than forcing several separate exports.",
      "## Keeping quality intact",
      "A well-built extraction tool copies pages directly without re-rendering, so fonts, image resolution, and interactive elements like form fields survive exactly as they were.",
      "## Where this actually gets used",
      "Pulling a single signed page — a signature page, an exhibit — out of a much larger legal document without sending the whole thing.",
    ],
  },
  {
    slug: "add-watermark-to-pdf",
    image: "/blog/add-watermark-to-pdf.svg",
    title: "How to Add a Watermark to a PDF",
    description:
      "Watermarks protect drafts and brand documents, but a badly placed one can make a document unreadable. Here's how to get it right.",
    category: "Guides",
    date: "2026-06-05",
    readTime: "4 min read",
    content: [
      "Watermarking is common for marking drafts, protecting confidential documents, or stamping a logo across every page — but get the settings wrong and the watermark does more harm than the thing it's protecting.",
      "## Text or image",
      "A text watermark — 'DRAFT,' 'CONFIDENTIAL' — is quick and works fine for internal use. An image watermark, like a logo, takes more setup but looks more polished for anything client-facing.",
      "## Opacity is where people mess up",
      "Leave it too high and the underlying text becomes hard to read. Somewhere around 10-20% is usually visible enough without fighting the actual content, especially on text-heavy pages.",
      "## Placement and angle",
      "A diagonal watermark across the center is the standard for a reason — hard to crop out, doesn't sit on top of any one line of text. A corner placement is easier to read past, but also easier to just crop off.",
      "## Not every page needs one",
      "Some tools let you watermark just the cover page, or skip pages that are blank or purely images. Handy if you want part of the document to look finished and part to clearly read as a draft.",
    ],
  },
  {
    slug: "ocr-scanned-pdf-to-text",
    image: "/blog/ocr-scanned-pdf-to-text.svg",
    title: "How to Use OCR to Extract Text From Scanned PDFs",
    description:
      "A scanned PDF is just a picture of text until OCR turns it into something you can actually search, copy, and edit. Here's how it works.",
    category: "Guides",
    date: "2026-06-08",
    readTime: "6 min read",
    content: [
      "However clean a scan looks, it's just a photograph as far as a computer's concerned — no real text at all. OCR is what reads the shapes on that image and turns them into actual, searchable, selectable text.",
      "## Why accuracy swings so much",
      "It comes down to scan quality. A clean, high-contrast scan of a typed page can hit 99%+ accuracy. A blurry photo of handwriting, faded ink, or a low-res fax can drop that dramatically — sometimes to the point of needing heavy manual correction.",
      "## Getting a better source scan",
      "300 DPI minimum for text documents, good even lighting, no angled shots. Scanning with a phone instead of a real scanner? Use auto-crop and auto-straighten to cut down on distortion before OCR runs.",
      "## What good OCR actually gives you",
      "Not just raw text — a searchable PDF that looks identical to the original scan but has an invisible text layer underneath, so you can search, copy, and highlight while the page still looks like a scan.",
      "## Multiple languages",
      "Most OCR engines need to know the language to recognize characters accurately, especially non-Latin scripts. Mixed-language document? Check whether your tool supports multi-language detection — forcing one language on a mixed document gives you garbage in the wrong sections.",
      "## Always proofread after",
      "Even good OCR trips over numbers — a '0' and an 'O', a '1' and an 'l' look alike. Proofread anything that matters: figures, dates, names. Don't trust it blindly.",
    ],
  },
  {
    slug: "pdf-vs-word-vs-google-docs",
    image: "/blog/pdf-vs-word-vs-google-docs.svg",
    title: "PDF vs Word vs Google Docs: Which Should You Use?",
    description:
      "Each format has a job it's genuinely good at. Here's how to pick the right one instead of defaulting to whatever's familiar.",
    category: "Comparisons",
    date: "2026-06-11",
    readTime: "5 min read",
    content: [
      "It's tempting to just use whichever format you're most comfortable with, but PDF, Word, and Google Docs are genuinely built for different jobs, and picking the right one now saves you a headache later.",
      "## PDF: final and fixed",
      "A PDF looks the same on every device and printer, no matter what fonts or software the recipient has. That's exactly why it's right for anything finished that shouldn't change — contracts, invoices, resumes, reports, anything going outside your organization.",
      "## Word: structured editing",
      "The right call when the recipient actually needs to edit — especially documents with heavy formatting, styles, tables of contents, or templates meant to be reused. It's also still the expected format in a lot of corporate and legal workflows, particularly ones using tracked changes.",
      "## Google Docs: real-time collaboration",
      "Built for multiple people editing at once, with autosave and simple version history. Right for drafts and brainstorming — anything actively being worked on together rather than finished and going out the door.",
      "## Moving between them",
      "Common pattern: draft in Google Docs or Word for the editing flexibility, export to PDF once it's done so the final version is locked and can't get accidentally changed by whoever opens it.",
      "## The simple rule",
      "Still being worked on? Word or Google Docs. Finished and needs to look the same for everyone? Convert to PDF before you send it.",
    ],
  },
  {
    slug: "fill-out-pdf-form-online",
    image: "/blog/fill-out-pdf-form-online.svg",
    title: "How to Fill Out a PDF Form Online",
    description:
      "Some PDF forms are fillable, some aren't, and treating them the same way leads to messy printouts. Here's how to tell the difference and fill either kind properly.",
    category: "Guides",
    date: "2026-06-14",
    readTime: "4 min read",
    content: [
      "PDF forms come in two flavors, and knowing which one you're looking at changes how you should fill it out.",
      "## Fillable vs. flat",
      "A fillable (interactive) form has real form fields — text boxes, checkboxes, dropdowns you click straight into. A flat form is just a page with lines and boxes drawn on it, no interactive fields at all.",
      "## Filling a fillable form",
      "Open it in a viewer that supports form fields, click each one, type your answer. Most viewers show a highlighted border or cursor over a real field — a quick way to confirm it's actually fillable before you start.",
      "## Filling a flat form",
      "You'll need an editor's text tool to manually place text boxes in the right spots — basically typing 'over' the printed lines. Takes more care to align, but looks a lot cleaner than printing and filling by hand.",
      "## Checkboxes and signatures on flat forms",
      "For checkbox-style fields, most editors let you drop in a checkmark or X exactly where it's needed. For a signature line, use a signature tool to place your signature image rather than trying to hand-draw it with a text tool.",
      "## Save a copy before submitting",
      "Especially for anything official — some submission methods, like uploading to a portal, won't give you a copy back afterward.",
    ],
  },
  {
    slug: "organizing-digital-documents",
    image: "/blog/organizing-digital-documents.svg",
    title: "Best Practices for Organizing Digital Documents",
    description:
      "A messy downloads folder full of scan(1).pdf, scan(2).pdf is a solvable problem. Here's a simple system that actually holds up over time.",
    category: "Productivity",
    date: "2026-06-17",
    readTime: "5 min read",
    content: [
      "Most people's document chaos isn't about having too many files — it's not having any consistent system for naming and storing them, so everything piles up wherever it happened to land.",
      "## A naming convention that actually sticks",
      "Date, then description, then version: '2026-06-17_electricity-bill_final.pdf'. Starting with the date means files sort chronologically automatically in any file browser, which is usually the order you'll actually want later.",
      "## Folders that don't collapse under their own weight",
      "Too many nested levels is as bad as no structure at all. Two or three levels — Category > Year > Files — tends to hold up much better than an elaborate hierarchy that made sense on day one and becomes a maze after a year.",
      "## Scanned paperwork",
      "Scan things as soon as they arrive instead of letting paper pile up, and OCR them so they're searchable. A folder of scans you can't search by content isn't much better than a physical filing cabinet.",
      "## Versioning without the chaos",
      "Skip the 'contract_final_v2_ACTUALLY_final.pdf' spiral. Use a simple incrementing number, and once something's genuinely final, rename it clearly and move earlier drafts into a separate subfolder.",
      "## Back it up",
      "Wherever it lives, make sure it's backed up somewhere other than one laptop's hard drive — cloud, external drive, both. A perfectly organized system does nothing for you if a single device failure wipes it out.",
    ],
  },
  {
    slug: "compress-pdf-for-email",
    image: "/blog/compress-pdf-for-email.svg",
    title: "How to Compress a PDF for Email",
    description:
      "Email attachment limits are stricter than most people realize. Here's how to get a PDF small enough to send without stripping out what matters.",
    category: "Guides",
    date: "2026-06-20",
    readTime: "4 min read",
    content: [
      "Most email providers cap attachments around 20-25MB, and plenty of everyday PDFs — scanned ones especially — blow past that without the sender realizing until the email bounces.",
      "## Check your actual limit",
      "It varies by provider, and sometimes by the recipient's own mailbox settings too. Not sure? Aim conservatively for under 10MB, which clears nearly every limit out there.",
      "## Compress before you send",
      "Start at medium compression — it usually cuts size significantly while keeping text and images legible. Check the result and only bump up to high if it's still too big.",
      "## When compression alone doesn't cut it",
      "A genuinely huge document — lots of high-res scans — might need to be split into two smaller files sent separately, or hosted on a cloud link instead of attached directly.",
      "## Sending several attachments at once",
      "Limits usually apply to the total of all attachments combined, not each file on its own. Compress every file in the batch, not just the biggest one — several medium files can add up past the limit just as easily as one large one.",
    ],
  },
  {
    slug: "common-pdf-errors-and-fixes",
    image: "/blog/common-pdf-errors-and-fixes.svg",
    title: "Common PDF Errors and How to Fix Them",
    description:
      "From 'file damaged' warnings to fonts that won't display, here are the most common PDF problems and the quickest way to solve each one.",
    category: "Troubleshooting",
    date: "2026-06-23",
    readTime: "6 min read",
    content: [
      "PDFs are generally reliable, but a handful of errors show up often enough that it's worth knowing the fix before assuming the file's a lost cause.",
      "## \"The file is damaged and could not be repaired\"",
      "Usually means the file got corrupted mid-transfer — an interrupted download, an incomplete upload. Try re-downloading or re-requesting from the original source first. A repair tool can sometimes recover a genuinely corrupted structure, but severe corruption often can't be fully fixed.",
      "## Fonts showing as boxes",
      "The PDF references a font that isn't embedded and isn't installed on the viewing device, so the viewer falls back to something else or shows blank boxes. The permanent fix is re-exporting the original with fonts embedded — most creation tools support this as an export option.",
      "## Blurry text on a different device",
      "Often just a rendering artifact of the viewer's zoom level, not an actual problem. Zoom to 100% or higher before trusting a shrunk-down preview. Still blurry at full zoom? The image was probably compressed too aggressively when the file was made.",
      "## \"Password protected\" when you don't remember setting one",
      "Some tools apply an owner-level restriction automatically without ever asking. Check whether it's actually blocking you from opening the file (real problem) or just blocking editing/printing (permissions restriction, not a lock).",
      "## Pages out of order after editing",
      "Usually happens after merging or reordering in a tool that doesn't show a clear page preview before saving. Always check the thumbnail view before finalizing anything that changes page order.",
      "## Won't open in a browser but opens fine in a PDF app",
      "Browser viewers tend to be stricter about malformed structure than dedicated readers. Try a proper PDF app instead — it's usually more forgiving of minor structural quirks.",
    ],
  },
  {
    slug: "edit-text-in-pdf",
    image: "/blog/edit-text-in-pdf.svg",
    title: "How to Edit Text in a PDF File",
    description:
      "PDFs weren't originally built to be edited, but modern tools make it possible. Here's what works well and what to expect from the process.",
    category: "Guides",
    date: "2026-06-26",
    readTime: "5 min read",
    content: [
      "PDF was designed as a fixed, final format, not an editable one — which is exactly why editing text in one still feels a little different from a word processor.",
      "## Text-based PDFs",
      "Made from Word or Google Docs originally? The text is real, selectable characters, so a good editor lets you click a line and modify it in place, matching font and size automatically.",
      "## Scanned PDFs",
      "No real text to click on — just an image. You either run OCR first to build an editable text layer, or cover the existing text with a white box and type over it, which works but won't perfectly match the original font.",
      "## Matching fonts",
      "A good editor tries to detect and match the surrounding font automatically. Unusual or custom fonts don't always get an exact match, so the tool substitutes the closest one — noticeable if you zoom in close.",
      "## Tables and columns",
      "The trickiest thing to edit directly, since the underlying structure isn't a real table the way it is in a word processor. For heavy edits here, it's often easier to convert to Word first, fix it there, and convert back.",
      "## After you're done",
      "Zoom in and check new text aligns properly and nothing overlaps or got pushed off the page — especially if you replaced something short with something longer.",
    ],
  },
  {
    slug: "convert-pdf-to-excel",
    image: "/blog/convert-pdf-to-excel.svg",
    title: "How to Convert a PDF to Excel",
    description:
      "Pulling tables out of a PDF and into a working spreadsheet is trickier than it sounds. Here's how to get clean, usable data.",
    category: "Convert",
    date: "2026-06-29",
    readTime: "5 min read",
    content: [
      "PDF to Excel is one of the harder conversions, because it's not just pulling text — it's reconstructing rows and columns from something that was never actually a spreadsheet to begin with.",
      "## Why tables are harder than plain text",
      "A PDF doesn't store 'tables' as data. What looks like one is just text and lines positioned at coordinates on the page. The converter has to guess where columns and rows begin and end purely from that layout — fine for clean tables, rough for merged cells or inconsistent spacing.",
      "## What converts cleanest",
      "Tables with visible grid lines and consistent column widths convert far more reliably than ones relying on whitespace alone. If you control how the source PDF gets made, bordered tables convert better than borderless ones.",
      "## Check after converting",
      "Open the spreadsheet and make sure numbers landed in the right columns, especially with several similar-looking columns of figures. Merged header cells are the most likely thing to break, often splitting unpredictably.",
      "## Convert, or just retype it",
      "For one small table, retyping it might genuinely be faster than converting a whole multi-page PDF and hunting for the table inside. Full conversion earns its keep with several pages of data you actually need to sort or run formulas on.",
      "## Formulas don't survive",
      "Converted spreadsheets bring over static values, not any formulas that generated them — a PDF has no concept of formulas. You'll rebuild any calculations directly in Excel.",
    ],
  },
  {
    slug: "convert-excel-to-pdf",
    image: "/blog/convert-excel-to-pdf.svg",
    title: "How to Convert Excel to PDF",
    description:
      "A spreadsheet that looks fine on your screen can print as a dozen cut-off pages. Here's how to convert it to PDF properly.",
    category: "Convert",
    date: "2026-07-01",
    readTime: "4 min read",
    content: [
      "Converting Excel to PDF seems trivial until you get fifteen pages of oddly split columns instead of the clean one-pager you expected.",
      "## Why it goes wrong",
      "Excel's print area and page layout settings — not your data — decide what ends up in the PDF. Never set a print area? Excel tries to print everything with data in it, often splitting wide tables across pages awkwardly.",
      "## Set the print area first",
      "Select only the cells you want, set them as the print area under Page Layout. This one step fixes most messy Excel-to-PDF conversions by stopping Excel from guessing.",
      "## Fitting it all on one page",
      "Use 'Scale to Fit' under Page Layout to shrink wide tables down instead of letting Excel split columns across pages. Especially useful for wide tables that aren't tall.",
      "## Orientation matters more than you'd think",
      "A wide table almost always converts cleaner in landscape than portrait — more horizontal room before Excel needs to split columns onto a second page.",
      "## Gridlines and headers",
      "Excel often skips printing gridlines and row/column headers by default, which is usually what you want for a clean PDF — but check the print preview if you specifically need them visible.",
    ],
  },
  {
    slug: "convert-powerpoint-to-pdf",
    image: "/blog/convert-powerpoint-to-pdf.svg",
    title: "How to Convert PowerPoint to PDF",
    description:
      "Sharing a deck as PDF avoids font and layout issues on other people's machines. Here's how to convert it without losing your design.",
    category: "Convert",
    date: "2026-07-03",
    readTime: "3 min read",
    content: [
      "Converting a deck to PDF is one of the more reliable ways to share it — it guarantees your slides look exactly the same on someone else's screen, regardless of which fonts or PowerPoint version they have.",
      "## Fonts are the real risk",
      "A custom or downloaded font not installed on the recipient's machine gets silently swapped for something else, which can shift text boxes and break your layout. Converting to PDF locks in the appearance so that can't happen.",
      "## Animations don't survive",
      "PDF is static — transitions, builds, embedded video don't carry over. Only the final state of each slide converts, which is fine for sharing but worth knowing if your deck leans on animated builds to make sense.",
      "## Slides only, or notes too",
      "Most tools default to exporting just the slide content. Want speaker notes included, for a version meant to be read rather than presented? Look for a 'notes pages' export option specifically.",
      "## Watch the file size",
      "Decks with lots of high-res images or video thumbnails can produce surprisingly large PDFs. Check the size afterward and compress if you're emailing it, same as with any image-heavy PDF.",
    ],
  },
  {
    slug: "combine-word-documents-into-pdf",
    image: "/blog/combine-word-documents-into-pdf.svg",
    title: "How to Combine Multiple Word Documents Into One PDF",
    description:
      "Stitching several Word files into a single polished PDF is a common need for reports and proposals. Here's the cleanest way to do it.",
    category: "Guides",
    date: "2026-07-05",
    readTime: "4 min read",
    content: [
      "Combining several Word files — different sections of a report written by different people, say — into one clean final PDF is common but a little fiddly without the right workflow.",
      "## Two approaches",
      "Convert each Word file to PDF individually and merge the results, or combine the Word docs into one file first and convert once. The second gives more control over consistent formatting; the first is faster when sections were formatted independently and don't need to match exactly.",
      "## Formatting clashes",
      "Different people writing different sections often means different fonts, heading styles, margins. Worth standardizing in Word before converting — fixing it after everything's a flattened PDF is much harder.",
      "## Getting page order right",
      "Whichever route you take, double-check final order carefully, especially when merging separately-converted PDFs. It's easy to combine files in the wrong sequence when you're juggling several similarly-named documents.",
      "## Cover page and numbering",
      "Once it's all one file, this is the right moment to add a shared cover page and continuous page numbering, rather than each section keeping the separate numbering it had as a standalone file.",
    ],
  },
  {
    slug: "add-page-numbers-to-pdf",
    image: "/blog/add-page-numbers-to-pdf.svg",
    title: "How to Add Page Numbers to a PDF",
    description:
      "Page numbers seem trivial until you need to add them to a document that didn't have any. Here's how to do it cleanly.",
    category: "Guides",
    date: "2026-07-07",
    readTime: "3 min read",
    content: [
      "Adding page numbers to an existing PDF comes up a lot, especially with documents assembled by merging several separately-created files that each started numbering at one.",
      "## Where numbering starts",
      "Got a cover page or table of contents you don't want numbered? Most tools let you start visible numbering later — say, page 3 — while still counting the cover pages internally. Standard in formal reports.",
      "## Placement and format",
      "Bottom-center, bottom-right, top-right are the usual spots, and formats range from a plain number to 'Page X of Y'. Pick a spot that won't collide with existing footer content, and check a few actual pages, not just the first one, before finalizing.",
      "## Numbering after a merge",
      "Old page numbers printed as part of the original content don't disappear when you add new ones on top — they'll just be wrong relative to the new combined count. For a clean result, you may need to remove old footers before adding new numbering.",
      "## Roman numerals for front matter",
      "Formal documents sometimes number a preface or table of contents with lowercase roman numerals before switching to regular numbers for the main content. Check whether your tool supports mixed schemes if that distinction matters.",
    ],
  },
  {
    slug: "add-table-of-contents-to-pdf",
    image: "/blog/add-table-of-contents-to-pdf.svg",
    title: "How to Add a Table of Contents to a PDF",
    description:
      "A long PDF without navigation is frustrating to use. Here's how to add a clickable table of contents that actually helps readers.",
    category: "Guides",
    date: "2026-07-09",
    readTime: "4 min read",
    content: [
      "A table of contents in a PDF isn't just a list of titles on a page — the useful version is clickable, letting readers jump straight to a section instead of scrolling through dozens of pages.",
      "## Bookmarks vs. an in-page TOC",
      "Bookmarks live in the viewer's sidebar and let readers navigate the document tree. An in-page TOC is a regular page with clickable links, visible even when printed. Stronger documents usually have both — bookmarks help digital readers, the in-page version helps anyone flipping through a printout.",
      "## Building the TOC page",
      "List each section with its page number, and turn each entry into a clickable link if your tool supports it. Keep it in sync manually if you edit afterward — automated syncing usually only exists in the original word processor, not in a finished PDF.",
      "## Adding bookmarks",
      "Most editors let you create a bookmark for a page, label it, and nest bookmarks into groups matching your document's structure. Worth doing for anything over roughly 15-20 pages, where scrolling alone gets tedious.",
      "## Test it before you send it",
      "Click through every entry and bookmark before finalizing — a link pointing to the wrong page is an easy mistake to miss, especially if pages got added or removed after the TOC was first built.",
    ],
  },
  {
    slug: "crop-pdf-pages",
    image: "/blog/crop-pdf-pages.svg",
    title: "How to Crop PDF Pages",
    description:
      "Trimming excess margins or unwanted content from a PDF page is a quick fix once you know where the crop boundary actually lives.",
    category: "Guides",
    date: "2026-07-11",
    readTime: "3 min read",
    content: [
      "Cropping removes visible margins or unwanted content around the edges without deleting anything from the actual page content — it just changes the visible boundary.",
      "## What cropping doesn't do",
      "Most crop tools don't permanently delete content — they adjust the visible boundary box while the full original content technically remains underneath. That makes cropping usually reversible, unlike something like removing a page outright.",
      "## Trimming wide margins",
      "A common reason to crop is a scan with a lot of excess white space, especially when the original was designed for a bigger page than the content needs. Tightening to just the content makes it look intentional on screen.",
      "## Consistency across pages",
      "Apply the same crop margins across a whole document rather than cropping page by page, unless individual pages genuinely need different treatment. Most tools let you set one boundary and apply it everywhere at once.",
      "## Crop vs. resize",
      "Cropping only trims visible edges, it doesn't change the actual page dimensions the way resizing does. Trying to fit A4 content onto Letter paper? You want a resize, not a crop.",
    ],
  },
  {
    slug: "resize-pdf-pages",
    image: "/blog/resize-pdf-pages.svg",
    title: "How to Resize PDF Pages",
    description:
      "Fitting a document made for one paper size onto another without cutting off content takes more than a simple scale. Here's how it works.",
    category: "Guides",
    date: "2026-07-13",
    readTime: "3 min read",
    content: [
      "Resizing changes actual page dimensions — different from zooming or cropping margins. Most often needed when a document made for one paper standard needs to work on another, like US Letter to A4.",
      "## The core problem",
      "Letter (8.5 x 11 in) and A4 (8.27 x 11.69 in) have different proportions, not just different sizes. A direct resize without adjustment can cut off content at the bottom or leave odd empty margins — which is why a 'resized' document still sometimes looks slightly off.",
      "## Scaling vs. reformatting",
      "A straightforward resize scales everything uniformly, which works for most documents but can make text a bit larger or smaller than expected. True reformatting — adjusting margins and layout specifically for the new size — looks cleaner but isn't something a basic resize tool does automatically.",
      "## Check margins after",
      "Make sure nothing important ended up too close to the new edges — printers typically can't print all the way to the physical edge and will clip anything positioned too close.",
      "## For repeated use",
      "If you regularly send documents internationally, set the source file (Word, Google Docs) to A4 from the start rather than resizing a finished PDF every time.",
    ],
  },
  {
    slug: "redact-sensitive-information-pdf",
    image: "/blog/redact-sensitive-information-pdf.svg",
    title: "How to Redact Sensitive Information in a PDF",
    description:
      "A black box drawn over text isn't real redaction, and it's a more common mistake than people realize. Here's how to redact properly.",
    category: "Security",
    date: "2026-07-15",
    readTime: "5 min read",
    content: [
      "Redaction has a genuinely dangerous failure mode: just drawing a black box over sensitive text often leaves the original text fully intact underneath — selectable and copyable the moment someone selects it.",
      "## Why covering isn't redacting",
      "A black box sitting on top of text is just another layer on the page — it doesn't remove or alter the text data at all. Copy the 'redacted' paragraph into another program, or open it in a viewer that handles layers differently, and the original text can come right back.",
      "## What real redaction requires",
      "Actually deleting the underlying text and image data in that area, permanently — not just hiding it visually. A genuine redaction tool will explicitly say it removes content, not just draws over it. That distinction is the single most important thing to check before trusting any tool with sensitive information.",
      "## Images and metadata too",
      "Sensitive info hides in more than visible text — a photographed document, hidden metadata like author names or comments. A thorough pass checks all three: text, images, metadata.",
      "## Verify it actually worked",
      "Try selecting text in the area you redacted. If you can still highlight and copy the words, the redaction failed — the content's still there, just hidden. Always run this check before sharing anything legally or professionally sensitive.",
    ],
  },
  {
    slug: "flatten-pdf-form",
    image: "/blog/flatten-pdf-form.svg",
    title: "How to Flatten a PDF Form",
    description:
      "Flattening locks a filled-out form so it can't be accidentally edited again. Here's what it does and when you actually need it.",
    category: "Guides",
    date: "2026-07-17",
    readTime: "3 min read",
    content: [
      "Flattening converts interactive, fillable fields into permanent, non-editable content — freezing whatever was entered so the fields behave like regular static text from that point on.",
      "## Why you'd bother",
      "Once a form's filled out and ready to submit or archive, flattening keeps anyone — including you, by accident — from changing the answers later. It also helps compatibility, since some viewers render fillable fields inconsistently but all of them render flattened static content the same.",
      "## What happens to the data",
      "The entered values get baked into the page as regular text or graphics, permanently replacing the interactive field. This is one-way — once flattened, you can't go back to editing individual answers except by manually editing the text like any other PDF content.",
      "## Not yet, if...",
      "If a form still needs more people to fill in fields — a multi-signer approval, say — don't flatten it yet. Flattening removes the exact fields the next person needs.",
      "## Part of archiving",
      "A common last step before archiving completed forms long-term — flattened files are simpler, more universally compatible, and immune to accidental edits of what should be a finalized record.",
    ],
  },
  {
    slug: "compare-two-pdf-files",
    image: "/blog/compare-two-pdf-files.svg",
    title: "How to Compare Two PDF Files for Differences",
    description:
      "Manually eyeballing two versions of a contract for changes is slow and unreliable. Here's how PDF comparison actually catches what changed.",
    category: "Comparisons",
    date: "2026-07-19",
    readTime: "4 min read",
    content: [
      "Comparing two versions of a contract by eye is slow and genuinely unreliable — small but important changes, like one digit in a price, are easy to miss scanning by hand.",
      "## Text comparison vs. visual comparison",
      "Text comparison extracts and compares actual content, flagging additions and deletions similar to tracked changes. Visual comparison overlays the pages as images and highlights pixel differences — more useful when formatting or layout matters as much as the words.",
      "## When text comparison won't work",
      "A scanned PDF with no real text layer gives a text-based tool nothing to compare. Either run OCR on both files first, or use a visual comparison tool that works directly with the page images.",
      "## Reading the report",
      "A good comparison tool shows you exactly what changed, usually color-coded like a code diff — not just that something changed. Skim the full report, not just the summary; summaries sometimes lump multiple distinct changes into one vague count.",
      "## Where this actually matters",
      "Contracts going through several rounds of negotiation, where confirming that only the agreed-upon changes happened — and nothing else — genuinely matters.",
    ],
  },
  {
    slug: "print-pdf-correctly",
    image: "/blog/print-pdf-correctly.svg",
    title: "How to Print a PDF Correctly (Without Cut-Off Margins)",
    description:
      "PDFs that look perfect on screen sometimes print with cropped edges or the wrong scale. Here's how to avoid that.",
    category: "Troubleshooting",
    date: "2026-07-21",
    readTime: "4 min read",
    content: [
      "A PDF that looks fine on screen can come out of a printer with cut-off edges or the wrong scale — and the cause is almost always the print dialog, not the file.",
      "## The \"Fit to Page\" trap",
      "Print dialogs default to fit-to-printable-area scaling more often than not, which can shrink or shift content slightly to accommodate the printer's unprintable margin — even when your document was already correctly sized. If it's meant to print at exactly its intended size, choose 'Actual Size' or '100%' instead.",
      "## Matching paper size",
      "PDF made for A4 but your dialog defaults to Letter (or the reverse)? Content near the bottom or right edge can get clipped even though the file's fine. Always confirm the paper size in the dialog matches what the document was designed for.",
      "## Unprintable margins are physical",
      "Nearly every printer has a small unprintable edge, typically a few millimeters, that no software setting can override — it's a hardware limit. Content placed very close to the page edge is always at some risk of clipping.",
      "## Check the preview",
      "Nearly every dialog shows exactly how the page will print, including where it'll be scaled or cropped. Check it, especially for tight margins or full-bleed images, rather than trusting the on-screen view alone.",
    ],
  },
  {
    slug: "resize-pdf-to-a4",
    image: "/blog/resize-pdf-to-a4.svg",
    title: "How to Resize a PDF to A4",
    description:
      "US Letter and A4 aren't the same shape, not just the same size. Here's how to convert one to the other without losing content.",
    category: "Guides",
    date: "2026-07-23",
    readTime: "3 min read",
    content: [
      "Converting Letter to A4 (or back) comes up constantly for anyone sharing documents internationally, since the US almost exclusively uses Letter and most of the world uses A4.",
      "## The size difference",
      "Letter is 8.5 x 11 in, A4 is 8.27 x 11.69 in — A4's slightly narrower and noticeably taller. Because the proportions differ, not just the area, a naive resize can leave empty space at the bottom or cut off content at the edge.",
      "## Scale, or crop-and-pad",
      "A scaling resize shrinks or stretches the whole page proportionally, keeping everything visible but slightly altering margins and spacing. Centering the content and padding or trimming margins instead preserves the original proportions better, at the cost of extra white space.",
      "## Check both margins",
      "After converting, check top/bottom and left/right — the Letter-to-A4 difference tends to show up most in vertical spacing.",
      "## Avoid the problem next time",
      "Regularly sending documents internationally? Set your source document to A4 from the start rather than resizing the PDF after the fact — it produces a cleaner result every time.",
    ],
  },
  {
    slug: "convert-html-to-pdf",
    image: "/blog/convert-html-to-pdf.svg",
    title: "How to Convert HTML to PDF",
    description:
      "Turning a web page into a clean PDF sounds simple but layouts, fonts, and interactive elements can all break in the process. Here's how to do it well.",
    category: "Convert",
    date: "2026-07-25",
    readTime: "4 min read",
    content: [
      "Turning a web page into a PDF is handy for archiving articles or turning a web report into something fixed and shareable — but web layouts don't always translate cleanly to a printed page.",
      "## Why some pages convert cleanly and others don't",
      "Simple, print-friendly layouts convert fine. Pages leaning on complex CSS grids, fixed-position elements, or JavaScript-rendered content can come out broken, missing content, or overlapping. Ad-heavy or cluttered sites tend to carry that clutter straight into the PDF unless the tool specifically filters it.",
      "## Your browser's built-in print-to-PDF",
      "Most modern browsers can save any page as a PDF straight from the print dialog — usually the fastest option, and it tends to respect the page's own print stylesheet if one exists. Worth trying before reaching for a dedicated tool.",
      "## Pages behind a login",
      "URL-based conversion tools generally can't access anything requiring a login, since they don't have your session. For those, your own browser's print-to-PDF while logged in is the more reliable option.",
      "## Keeping links clickable",
      "A well-converted file keeps hyperlinks actually clickable, not just styled like blue text. Test a few after converting if that matters for your use case.",
    ],
  },
  {
    slug: "convert-pdf-to-html",
    image: "/blog/convert-pdf-to-html.svg",
    title: "How to Convert PDF to HTML",
    description:
      "Turning a PDF into a web page is useful for publishing content online, but the layout rarely survives the trip unchanged. Here's what to expect.",
    category: "Convert",
    date: "2026-07-27",
    readTime: "4 min read",
    content: [
      "PDF to HTML is the reverse of the more common direction, and it's generally the harder conversion — PDF is fixed-layout, HTML is meant to reflow across screen sizes.",
      "## Why the layout doesn't always survive",
      "A PDF places text and images at exact coordinates on a fixed page. Responsive HTML doesn't work that way at all. The converter has to make judgment calls about what to preserve and what to let reflow, and it doesn't always guess right — especially with multi-column layouts or heavily designed pages.",
      "## What converts well",
      "Simple, single-column, mostly-text PDFs — a basic report or article — convert to reasonably clean HTML. Brochures, infographics, anything with overlapping text and graphics convert far less predictably.",
      "## Expect some cleanup",
      "Image placement, heading structure, and tables are the usual trouble spots. Treat conversion output as a solid first draft, not a finished, publish-ready page.",
      "## Sometimes it's faster to just rebuild",
      "For something important becoming a genuinely good web page — a long report turning into a blog post — it's often faster to manually rebuild in HTML using the PDF as a reference than to fight an automated conversion into looking right.",
    ],
  },
  {
    slug: "pdf-a-archiving-guide",
    image: "/blog/pdf-a-archiving-guide.svg",
    title: "PDF/A Explained: How to Archive PDFs for the Long Term",
    description:
      "A regular PDF isn't actually guaranteed to open the same way in twenty years. Here's what PDF/A is and when you actually need it.",
    category: "Productivity",
    date: "2026-07-29",
    readTime: "4 min read",
    content: [
      "It's easy to assume any PDF just opens forever, but a standard PDF can rely on things like external fonts, embedded video, encryption, or JavaScript that future software might not support the same way. PDF/A exists specifically to solve that.",
      "## What makes it different",
      "PDF/A is a stricter subset of the format, built for long-term archiving. It requires every font to be embedded directly (so nothing depends on fonts being installed later), disallows JavaScript and external links, and disallows encryption — all specifically to guarantee the document renders identically decades from now.",
      "## Who actually needs it",
      "An everyday resume or this week's invoice doesn't. Legal records, government filings, medical records, institutional archives — anything that must stay readable and unchanged for years and may face compliance requirements — does.",
      "## Converting to PDF/A",
      "Most conversion tools check your file for anything violating the standard — missing embedded fonts, JavaScript — and either fix it automatically or flag it for you to address before finishing.",
      "## A common misconception",
      "PDF/A isn't a different-looking file or a special reader — it opens and displays exactly like a normal PDF in any standard viewer. The difference is entirely in what's technically permitted inside, to guarantee long-term compatibility.",
    ],
  },
  {
    slug: "scanned-photos-to-searchable-pdf",
    image: "/blog/scanned-photos-to-searchable-pdf.svg",
    title: "How to Turn Scanned Photos Into a Searchable PDF",
    description:
      "A pile of scanned document photos isn't useful until you can actually search it. Here's how to build a searchable archive properly.",
    category: "Guides",
    date: "2026-07-31",
    readTime: "5 min read",
    content: [
      "Scanning a stack of paperwork into PDF is only half the job. Without OCR, that scanned PDF is just page images — you can't search for a word, an invoice number, a name anywhere in it, which kind of defeats the point of digitizing in the first place.",
      "## Combine first, then OCR",
      "The efficient workflow: combine multiple scanned photos into one PDF first, then run OCR across the whole thing in one pass, rather than OCR-ing each photo before combining. Simpler, and keeps recognition settings consistent across every page.",
      "## Better photos before OCR",
      "Straighten and crop each photo so the document fills the frame with minimal background, and keep lighting even without harsh shadows. Cleaner photos translate directly into more accurate OCR.",
      "## What makes it genuinely searchable",
      "A properly OCR'd PDF keeps the original scanned images visible while adding an invisible text layer underneath — looks exactly like the scan but can be searched, copied from, and indexed by your OS's file search.",
      "## Once it's searchable",
      "Naming and folders matter less for finding things once you can search by content, but a basic consistent system is still worth keeping for browsing and backup.",
    ],
  },
  {
    slug: "add-bookmarks-to-pdf",
    image: "/blog/add-bookmarks-to-pdf.svg",
    title: "How to Add Bookmarks to a PDF",
    description:
      "PDF bookmarks are the sidebar navigation most long documents are missing. Here's how to add them so readers can actually find their way around.",
    category: "Guides",
    date: "2026-08-02",
    readTime: "3 min read",
    content: [
      "Bookmarks show up as a collapsible navigation tree in most PDF viewers' sidebar, letting readers jump straight to a chapter instead of scrolling the whole document to find it.",
      "## Worth adding, or not",
      "Anything over roughly 15-20 pages with distinct sections — a report, manual, long proposal — benefits. A five-page document doesn't; scrolling through that isn't a real burden the way it is with an eighty-pager.",
      "## Creating one",
      "Navigate to the exact page and position, create a bookmark, give it a clear label — ideally matching the actual heading text so readers aren't confused by mismatched names.",
      "## Nesting them",
      "For documents with subsections, nest bookmarks under their parent chapter instead of one long flat list. Most tools support drag-and-drop nesting in the bookmark panel.",
      "## Bookmarks aren't a substitute for a TOC",
      "They only help digital readers — they don't appear when printed. If the document might get printed too, pair bookmarks with an actual table of contents page so navigation works both ways.",
    ],
  },
  {
    slug: "insert-blank-page-into-pdf",
    image: "/blog/insert-blank-page-into-pdf.svg",
    title: "How to Insert a Blank Page Into a PDF",
    description:
      "Sometimes you need an empty page for notes, a divider, or print pagination. Here's the quickest way to add one.",
    category: "Guides",
    date: "2026-08-04",
    readTime: "2 min read",
    content: [
      "Inserting a blank page is small but comes up often — a notes page, a section divider, or just forcing a document to end on an even page for double-sided printing.",
      "## Where it goes",
      "Decide whether it goes before or after a specific page, and check your page count beforehand — easy to miscount by one in a long document.",
      "## Matching page size",
      "Make sure the blank page matches the surrounding document's size. An A4 doc with an accidentally Letter-sized blank page looks inconsistent and can cause printing issues. Most tools match the adjacent page automatically, but worth confirming.",
      "## For double-sided printing",
      "Need a new section to always start on a right-hand (odd-numbered) page? Inserting a blank page before it forces that alignment — the same trick used in professionally printed books.",
      "## Removing it later",
      "It's just a regular page as far as the PDF's concerned — removing it later uses the same process as deleting any other page.",
    ],
  },
  {
    slug: "recover-text-from-corrupted-pdf",
    image: "/blog/recover-text-from-corrupted-pdf.svg",
    title: "How to Recover Text From a Corrupted PDF",
    description:
      "A corrupted PDF isn't always a total loss. Here's what recovery actually involves and when it's realistic to expect success.",
    category: "Troubleshooting",
    date: "2026-08-06",
    readTime: "4 min read",
    content: [
      "A corrupted PDF — one that won't open or throws a damage error — isn't automatically unrecoverable, but success depends heavily on what went wrong and how badly the internal structure got hit.",
      "## What usually causes it",
      "An interrupted download or transfer, a crash mid-save, or a storage error while the file was being written. The cause matters, since a partially-downloaded file is a very different repair problem than one damaged by a failing drive.",
      "## Try a repair tool first",
      "Repair tools scan for whatever valid data remains and try to rebuild a working document around it. Works reasonably well for minor structural damage, but often can't fully recover files missing large chunks entirely.",
      "## When you only get some of it back",
      "Sometimes a repair tool recovers some pages but not others. Exporting whatever it does successfully extract — even as partial content or plain text — is a reasonable fallback if the complete original isn't recoverable.",
      "## Prevent it next time",
      "Keep an unmodified backup separate from your working copy, and avoid saving over a file mid-transfer or mid-download. A little backup discipline beats trying to recover a corrupted file after the fact, every time.",
    ],
  },
];

export function getAllPosts(): BlogPost[] {
  return [...blogPosts].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}

export function getAllSlugs(): string[] {
  return blogPosts.map((post) => post.slug);
}